// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_Success                   ErrorCode = 0
	ErrorCode_ErrorNameUsed             ErrorCode = 300001
	ErrorCode_ErrorEmailRegistered      ErrorCode = 300002
	ErrorCode_ErrorNamePasswordMisMatch ErrorCode = 300003
	ErrorCode_ErrorNotActivated         ErrorCode = 30004
)

var ErrorCode_name = map[int32]string{
	0:      "Success",
	300001: "ErrorNameUsed",
	300002: "ErrorEmailRegistered",
	300003: "ErrorNamePasswordMisMatch",
	30004:  "ErrorNotActivated",
}
var ErrorCode_value = map[string]int32{
	"Success":                   0,
	"ErrorNameUsed":             300001,
	"ErrorEmailRegistered":      300002,
	"ErrorNamePasswordMisMatch": 300003,
	"ErrorNotActivated":         30004,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_account_147c02a51765ec75, []int{0}
}

type RegisterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_147c02a51765ec75, []int{0}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_147c02a51765ec75, []int{1}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

type LoginRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_147c02a51765ec75, []int{2}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string       `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	Info                 *AccountInfo `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_147c02a51765ec75, []int{3}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetInfo() *AccountInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type AccountInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_147c02a51765ec75, []int{4}
}
func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (dst *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(dst, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AccountInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *AccountInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type AccountIdRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountIdRequest) Reset()         { *m = AccountIdRequest{} }
func (m *AccountIdRequest) String() string { return proto.CompactTextString(m) }
func (*AccountIdRequest) ProtoMessage()    {}
func (*AccountIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_147c02a51765ec75, []int{5}
}
func (m *AccountIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountIdRequest.Unmarshal(m, b)
}
func (m *AccountIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountIdRequest.Marshal(b, m, deterministic)
}
func (dst *AccountIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountIdRequest.Merge(dst, src)
}
func (m *AccountIdRequest) XXX_Size() int {
	return xxx_messageInfo_AccountIdRequest.Size(m)
}
func (m *AccountIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountIdRequest proto.InternalMessageInfo

func (m *AccountIdRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type AccountName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountName) Reset()         { *m = AccountName{} }
func (m *AccountName) String() string { return proto.CompactTextString(m) }
func (*AccountName) ProtoMessage()    {}
func (*AccountName) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_147c02a51765ec75, []int{6}
}
func (m *AccountName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountName.Unmarshal(m, b)
}
func (m *AccountName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountName.Marshal(b, m, deterministic)
}
func (dst *AccountName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountName.Merge(dst, src)
}
func (m *AccountName) XXX_Size() int {
	return xxx_messageInfo_AccountName.Size(m)
}
func (m *AccountName) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountName.DiscardUnknown(m)
}

var xxx_messageInfo_AccountName proto.InternalMessageInfo

func (m *AccountName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AccountIdResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountIdResponse) Reset()         { *m = AccountIdResponse{} }
func (m *AccountIdResponse) String() string { return proto.CompactTextString(m) }
func (*AccountIdResponse) ProtoMessage()    {}
func (*AccountIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_147c02a51765ec75, []int{7}
}
func (m *AccountIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountIdResponse.Unmarshal(m, b)
}
func (m *AccountIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountIdResponse.Marshal(b, m, deterministic)
}
func (dst *AccountIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountIdResponse.Merge(dst, src)
}
func (m *AccountIdResponse) XXX_Size() int {
	return xxx_messageInfo_AccountIdResponse.Size(m)
}
func (m *AccountIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountIdResponse proto.InternalMessageInfo

func (m *AccountIdResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type AccountsBasicInfoRequest struct {
	Uids                 []string `protobuf:"bytes,1,rep,name=uids" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountsBasicInfoRequest) Reset()         { *m = AccountsBasicInfoRequest{} }
func (m *AccountsBasicInfoRequest) String() string { return proto.CompactTextString(m) }
func (*AccountsBasicInfoRequest) ProtoMessage()    {}
func (*AccountsBasicInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_147c02a51765ec75, []int{8}
}
func (m *AccountsBasicInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsBasicInfoRequest.Unmarshal(m, b)
}
func (m *AccountsBasicInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsBasicInfoRequest.Marshal(b, m, deterministic)
}
func (dst *AccountsBasicInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsBasicInfoRequest.Merge(dst, src)
}
func (m *AccountsBasicInfoRequest) XXX_Size() int {
	return xxx_messageInfo_AccountsBasicInfoRequest.Size(m)
}
func (m *AccountsBasicInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsBasicInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsBasicInfoRequest proto.InternalMessageInfo

func (m *AccountsBasicInfoRequest) GetUids() []string {
	if m != nil {
		return m.Uids
	}
	return nil
}

type AccountsBasicInfoResponse struct {
	Infos                []*BasicInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AccountsBasicInfoResponse) Reset()         { *m = AccountsBasicInfoResponse{} }
func (m *AccountsBasicInfoResponse) String() string { return proto.CompactTextString(m) }
func (*AccountsBasicInfoResponse) ProtoMessage()    {}
func (*AccountsBasicInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_147c02a51765ec75, []int{9}
}
func (m *AccountsBasicInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsBasicInfoResponse.Unmarshal(m, b)
}
func (m *AccountsBasicInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsBasicInfoResponse.Marshal(b, m, deterministic)
}
func (dst *AccountsBasicInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsBasicInfoResponse.Merge(dst, src)
}
func (m *AccountsBasicInfoResponse) XXX_Size() int {
	return xxx_messageInfo_AccountsBasicInfoResponse.Size(m)
}
func (m *AccountsBasicInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsBasicInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsBasicInfoResponse proto.InternalMessageInfo

func (m *AccountsBasicInfoResponse) GetInfos() []*BasicInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type BasicInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicInfo) Reset()         { *m = BasicInfo{} }
func (m *BasicInfo) String() string { return proto.CompactTextString(m) }
func (*BasicInfo) ProtoMessage()    {}
func (*BasicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_147c02a51765ec75, []int{10}
}
func (m *BasicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicInfo.Unmarshal(m, b)
}
func (m *BasicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicInfo.Marshal(b, m, deterministic)
}
func (dst *BasicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicInfo.Merge(dst, src)
}
func (m *BasicInfo) XXX_Size() int {
	return xxx_messageInfo_BasicInfo.Size(m)
}
func (m *BasicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BasicInfo proto.InternalMessageInfo

func (m *BasicInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BasicInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BasicInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "account.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "account.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "account.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "account.LoginResponse")
	proto.RegisterType((*AccountInfo)(nil), "account.AccountInfo")
	proto.RegisterType((*AccountIdRequest)(nil), "account.AccountIdRequest")
	proto.RegisterType((*AccountName)(nil), "account.AccountName")
	proto.RegisterType((*AccountIdResponse)(nil), "account.AccountIdResponse")
	proto.RegisterType((*AccountsBasicInfoRequest)(nil), "account.AccountsBasicInfoRequest")
	proto.RegisterType((*AccountsBasicInfoResponse)(nil), "account.AccountsBasicInfoResponse")
	proto.RegisterType((*BasicInfo)(nil), "account.BasicInfo")
	proto.RegisterEnum("account.ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_account_147c02a51765ec75) }

var fileDescriptor_account_147c02a51765ec75 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x6e, 0x13, 0x3f,
	0x10, 0xfe, 0x6d, 0xfe, 0xb4, 0xc9, 0xe4, 0x97, 0xb2, 0x1d, 0x42, 0xd9, 0xac, 0x84, 0x48, 0x2d,
	0x21, 0x45, 0x1c, 0x72, 0x08, 0x12, 0xd7, 0x2a, 0x41, 0x11, 0x42, 0xa2, 0x80, 0x52, 0x10, 0x12,
	0x17, 0x64, 0x76, 0x9d, 0xd6, 0x82, 0xae, 0x83, 0xed, 0x0d, 0xe2, 0xcc, 0xc3, 0xe4, 0x05, 0x78,
	0x21, 0xe0, 0xd6, 0xa7, 0x40, 0xf6, 0x7a, 0x9d, 0x28, 0x59, 0x71, 0x81, 0x53, 0x3c, 0x33, 0x9f,
	0xbf, 0x99, 0xfd, 0xfc, 0x4d, 0xa0, 0x4b, 0x93, 0x44, 0xe4, 0x99, 0x1e, 0x2d, 0xa5, 0xd0, 0x02,
	0x0f, 0x5d, 0x48, 0xde, 0xc2, 0xad, 0x39, 0xbb, 0xe4, 0x4a, 0x33, 0x39, 0x67, 0x9f, 0x73, 0xa6,
	0x34, 0x22, 0x34, 0x32, 0x7a, 0xcd, 0xa2, 0x60, 0x10, 0x0c, 0xdb, 0x73, 0x7b, 0xc6, 0x1e, 0x34,
	0xd9, 0x35, 0xe5, 0x9f, 0xa2, 0x9a, 0x4d, 0x16, 0x01, 0xc6, 0xd0, 0x5a, 0x52, 0xa5, 0xbe, 0x08,
	0x99, 0x46, 0x75, 0x5b, 0xf0, 0x31, 0x41, 0x08, 0x37, 0xc4, 0x6a, 0x29, 0x32, 0xc5, 0xc8, 0x6b,
	0xf8, 0xff, 0xb9, 0xb8, 0xe4, 0xd9, 0xbf, 0xed, 0xf4, 0x12, 0xba, 0x8e, 0xb5, 0x68, 0x63, 0x28,
	0xb4, 0xf8, 0xc8, 0x32, 0x87, 0x2c, 0x02, 0x1c, 0x42, 0x83, 0x67, 0x0b, 0x11, 0x35, 0x06, 0xc1,
	0xb0, 0x33, 0xee, 0x8d, 0x4a, 0x41, 0x26, 0xc5, 0xef, 0xb3, 0x6c, 0x21, 0xe6, 0x16, 0x41, 0xae,
	0xa0, 0xb3, 0x95, 0xc4, 0x23, 0xa8, 0xf1, 0xd4, 0xcd, 0x58, 0xe3, 0xa9, 0x9f, 0xba, 0xb6, 0x35,
	0xf5, 0x09, 0x1c, 0xd0, 0x15, 0xd5, 0x54, 0xba, 0x9e, 0x2e, 0xc2, 0x7b, 0x00, 0x89, 0x64, 0x54,
	0xb3, 0xf4, 0x3d, 0xd5, 0xb6, 0x75, 0x7d, 0xde, 0x76, 0x99, 0x89, 0x26, 0x23, 0x08, 0xcb, 0x4e,
	0x69, 0x29, 0x4a, 0x0c, 0xad, 0x5c, 0x31, 0xb9, 0x25, 0x8c, 0x8f, 0xc9, 0xa9, 0x9f, 0xec, 0x85,
	0xe9, 0x5a, 0xa1, 0x1f, 0x79, 0x00, 0xc7, 0x5b, 0x94, 0x4e, 0x91, 0x10, 0xea, 0xb9, 0xff, 0x06,
	0x73, 0x24, 0x23, 0x88, 0x1c, 0x4c, 0x4d, 0xa9, 0xe2, 0x89, 0xfd, 0xfc, 0xcd, 0xb3, 0xe4, 0x3c,
	0x55, 0x51, 0x30, 0xa8, 0x1b, 0x5a, 0x73, 0x26, 0x33, 0xe8, 0x57, 0xe0, 0x1d, 0xfd, 0x10, 0x9a,
	0x46, 0xb8, 0xe2, 0x46, 0x67, 0x8c, 0x5e, 0xdb, 0x0d, 0xb4, 0x00, 0x90, 0xa7, 0xd0, 0xf6, 0xb9,
	0xbf, 0x11, 0xf6, 0xe1, 0xb7, 0x00, 0xda, 0x33, 0x29, 0x85, 0x7c, 0x22, 0x52, 0x86, 0x1d, 0x38,
	0xbc, 0xc8, 0x93, 0x84, 0x29, 0x15, 0xfe, 0x87, 0xb7, 0xa1, 0x6b, 0x2b, 0x46, 0xa2, 0x37, 0x8a,
	0xa5, 0xe1, 0x8f, 0x35, 0x62, 0x0c, 0x3d, 0x9b, 0x9c, 0x19, 0x3b, 0x95, 0xc6, 0x64, 0x69, 0xf8,
	0x73, 0x8d, 0x78, 0x1f, 0xfa, 0xfe, 0xc2, 0x2b, 0xe7, 0xaa, 0x73, 0xae, 0xce, 0xa9, 0x4e, 0xae,
	0xc2, 0x5f, 0x6b, 0xc4, 0xbb, 0x70, 0x5c, 0x00, 0x84, 0x9e, 0x24, 0x9a, 0xaf, 0xcc, 0xeb, 0x85,
	0xdf, 0x6f, 0x82, 0xf1, 0x4d, 0x0d, 0x8e, 0x9c, 0x2c, 0x17, 0x4c, 0xae, 0x78, 0xc2, 0xf0, 0x0c,
	0x5a, 0x25, 0x3d, 0x46, 0x5e, 0x88, 0x9d, 0x1d, 0x8b, 0xfb, 0x15, 0x15, 0x27, 0xe6, 0x63, 0x68,
	0x5a, 0x3b, 0xe3, 0x1d, 0x8f, 0xd9, 0x5e, 0x9a, 0xf8, 0x64, 0x37, 0xed, 0xee, 0x4d, 0xa1, 0xed,
	0x1f, 0x1e, 0xfb, 0x7b, 0xf6, 0x2e, 0xfd, 0x15, 0xc7, 0x55, 0x25, 0xc7, 0x71, 0xb6, 0x31, 0x4f,
	0xb6, 0x10, 0xd3, 0xaf, 0xd6, 0x65, 0x7b, 0xab, 0x62, 0xb2, 0x71, 0xe5, 0x02, 0xe1, 0x3b, 0x4f,
	0xb0, 0xb1, 0x09, 0x9e, 0xee, 0x42, 0xf7, 0x2c, 0x17, 0x93, 0x3f, 0x41, 0x8a, 0xe1, 0x3e, 0x1c,
	0xd8, 0xbf, 0xae, 0x47, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x52, 0x59, 0xc6, 0xcb, 0x04,
	0x00, 0x00,
}
