// Code generated by protoc-gen-go. DO NOT EDIT.
// source: syntect.proto

package syntect

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CodeTheme int32

const (
	CodeTheme_SolarizedDark  CodeTheme = 0
	CodeTheme_SolarizedLight CodeTheme = 1
)

var CodeTheme_name = map[int32]string{
	0: "SolarizedDark",
	1: "SolarizedLight",
}
var CodeTheme_value = map[string]int32{
	"SolarizedDark":  0,
	"SolarizedLight": 1,
}

func (x CodeTheme) String() string {
	return proto.EnumName(CodeTheme_name, int32(x))
}
func (CodeTheme) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_syntect_428847c2a0f89598, []int{0}
}

type RenderCodeRequest struct {
	File                 string    `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Code                 string    `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Theme                CodeTheme `protobuf:"varint,3,opt,name=theme,enum=syntect.CodeTheme" json:"theme,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RenderCodeRequest) Reset()         { *m = RenderCodeRequest{} }
func (m *RenderCodeRequest) String() string { return proto.CompactTextString(m) }
func (*RenderCodeRequest) ProtoMessage()    {}
func (*RenderCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_syntect_428847c2a0f89598, []int{0}
}
func (m *RenderCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderCodeRequest.Unmarshal(m, b)
}
func (m *RenderCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderCodeRequest.Marshal(b, m, deterministic)
}
func (dst *RenderCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderCodeRequest.Merge(dst, src)
}
func (m *RenderCodeRequest) XXX_Size() int {
	return xxx_messageInfo_RenderCodeRequest.Size(m)
}
func (m *RenderCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenderCodeRequest proto.InternalMessageInfo

func (m *RenderCodeRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *RenderCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RenderCodeRequest) GetTheme() CodeTheme {
	if m != nil {
		return m.Theme
	}
	return CodeTheme_SolarizedDark
}

type RenderCodeResponse struct {
	RenderedCode         string   `protobuf:"bytes,1,opt,name=renderedCode" json:"renderedCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderCodeResponse) Reset()         { *m = RenderCodeResponse{} }
func (m *RenderCodeResponse) String() string { return proto.CompactTextString(m) }
func (*RenderCodeResponse) ProtoMessage()    {}
func (*RenderCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_syntect_428847c2a0f89598, []int{1}
}
func (m *RenderCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderCodeResponse.Unmarshal(m, b)
}
func (m *RenderCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderCodeResponse.Marshal(b, m, deterministic)
}
func (dst *RenderCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderCodeResponse.Merge(dst, src)
}
func (m *RenderCodeResponse) XXX_Size() int {
	return xxx_messageInfo_RenderCodeResponse.Size(m)
}
func (m *RenderCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenderCodeResponse proto.InternalMessageInfo

func (m *RenderCodeResponse) GetRenderedCode() string {
	if m != nil {
		return m.RenderedCode
	}
	return ""
}

func init() {
	proto.RegisterType((*RenderCodeRequest)(nil), "syntect.RenderCodeRequest")
	proto.RegisterType((*RenderCodeResponse)(nil), "syntect.RenderCodeResponse")
	proto.RegisterEnum("syntect.CodeTheme", CodeTheme_name, CodeTheme_value)
}

func init() { proto.RegisterFile("syntect.proto", fileDescriptor_syntect_428847c2a0f89598) }

var fileDescriptor_syntect_428847c2a0f89598 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x31, 0x3f, 0xd5, 0x13, 0x8d, 0xda, 0x9b, 0xa2, 0xb2, 0x54, 0x99, 0x22, 0x86, 0x0c,
	0x61, 0x61, 0x07, 0x36, 0x26, 0x07, 0x89, 0x39, 0xc4, 0x0f, 0x62, 0x11, 0xe2, 0x60, 0x1b, 0x24,
	0xf8, 0xeb, 0x91, 0xe3, 0x10, 0x40, 0x74, 0x3b, 0x7f, 0x67, 0xbd, 0xef, 0xd9, 0xb4, 0x74, 0x1f,
	0xbd, 0x47, 0xe3, 0x8b, 0xc1, 0x1a, 0x6f, 0xf8, 0x64, 0x3a, 0x66, 0xa0, 0xb5, 0x44, 0xaf, 0x60,
	0xaf, 0x8c, 0x82, 0xc4, 0xeb, 0x1b, 0x9c, 0x67, 0xa6, 0xc3, 0x47, 0xdd, 0x21, 0x15, 0x5b, 0x91,
	0x2f, 0xe4, 0x38, 0x07, 0xd6, 0x18, 0x85, 0x74, 0x3f, 0xb2, 0x30, 0x73, 0x4e, 0x47, 0xbe, 0xc5,
	0x0b, 0xd2, 0x83, 0xad, 0xc8, 0x93, 0x92, 0x8b, 0x6f, 0x49, 0x08, 0xbb, 0x0b, 0x1b, 0x19, 0x2f,
	0x64, 0x97, 0xc4, 0xbf, 0x35, 0x6e, 0x30, 0xbd, 0x03, 0x67, 0x74, 0x6a, 0x47, 0x0a, 0x15, 0xf8,
	0xe4, 0xfb, 0xc3, 0xce, 0x4b, 0x5a, 0xcc, 0x69, 0xbc, 0xa6, 0x65, 0x65, 0xba, 0xda, 0xea, 0x4f,
	0xa8, 0xeb, 0xda, 0x3e, 0xaf, 0xf6, 0x98, 0x29, 0x99, 0xd1, 0xad, 0x7e, 0x6a, 0xfd, 0x4a, 0x94,
	0xf7, 0x94, 0x54, 0xb1, 0x49, 0x05, 0xfb, 0xae, 0x1b, 0xf0, 0x0d, 0xd1, 0x8f, 0x9f, 0x37, 0x73,
	0xd1, 0x7f, 0x6f, 0xdf, 0x9c, 0xed, 0xdc, 0xc5, 0xc2, 0x0f, 0xc7, 0xe3, 0xef, 0x5d, 0x7c, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xff, 0x47, 0x03, 0x11, 0x4e, 0x01, 0x00, 0x00,
}
