// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: syntect.proto

package syntect

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SyntectService service

type SyntectService interface {
	RenderCode(ctx context.Context, in *RenderCodeRequest, opts ...client.CallOption) (*RenderCodeResponse, error)
}

type syntectService struct {
	c    client.Client
	name string
}

func NewSyntectService(name string, c client.Client) SyntectService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "syntect"
	}
	return &syntectService{
		c:    c,
		name: name,
	}
}

func (c *syntectService) RenderCode(ctx context.Context, in *RenderCodeRequest, opts ...client.CallOption) (*RenderCodeResponse, error) {
	req := c.c.NewRequest(c.name, "SyntectService.RenderCode", in)
	out := new(RenderCodeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SyntectService service

type SyntectServiceHandler interface {
	RenderCode(context.Context, *RenderCodeRequest, *RenderCodeResponse) error
}

func RegisterSyntectServiceHandler(s server.Server, hdlr SyntectServiceHandler, opts ...server.HandlerOption) error {
	type syntectService interface {
		RenderCode(ctx context.Context, in *RenderCodeRequest, out *RenderCodeResponse) error
	}
	type SyntectService struct {
		syntectService
	}
	h := &syntectServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SyntectService{h}, opts...))
}

type syntectServiceHandler struct {
	SyntectServiceHandler
}

func (h *syntectServiceHandler) RenderCode(ctx context.Context, in *RenderCodeRequest, out *RenderCodeResponse) error {
	return h.SyntectServiceHandler.RenderCode(ctx, in, out)
}
