// Code generated by protoc-gen-go. DO NOT EDIT.
// source: repository.proto

package repository

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RepositoryErrorCode int32

const (
	RepositoryErrorCode_Success            RepositoryErrorCode = 0
	RepositoryErrorCode_InSync             RepositoryErrorCode = 200001
	RepositoryErrorCode_RepositoryNotFound RepositoryErrorCode = 200002
	RepositoryErrorCode_DirectoryNotFound  RepositoryErrorCode = 200003
)

var RepositoryErrorCode_name = map[int32]string{
	0:      "Success",
	200001: "InSync",
	200002: "RepositoryNotFound",
	200003: "DirectoryNotFound",
}
var RepositoryErrorCode_value = map[string]int32{
	"Success":            0,
	"InSync":             200001,
	"RepositoryNotFound": 200002,
	"DirectoryNotFound":  200003,
}

func (x RepositoryErrorCode) String() string {
	return proto.EnumName(RepositoryErrorCode_name, int32(x))
}
func (RepositoryErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_repository_0518ff3e483ebad8, []int{0}
}

type NamedCommitsRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedCommitsRequest) Reset()         { *m = NamedCommitsRequest{} }
func (m *NamedCommitsRequest) String() string { return proto.CompactTextString(m) }
func (*NamedCommitsRequest) ProtoMessage()    {}
func (*NamedCommitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_0518ff3e483ebad8, []int{0}
}
func (m *NamedCommitsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedCommitsRequest.Unmarshal(m, b)
}
func (m *NamedCommitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedCommitsRequest.Marshal(b, m, deterministic)
}
func (dst *NamedCommitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedCommitsRequest.Merge(dst, src)
}
func (m *NamedCommitsRequest) XXX_Size() int {
	return xxx_messageInfo_NamedCommitsRequest.Size(m)
}
func (m *NamedCommitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedCommitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NamedCommitsRequest proto.InternalMessageInfo

func (m *NamedCommitsRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type NamedCommitsResponse struct {
	Commits              []*NamedCommit `protobuf:"bytes,3,rep,name=commits" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NamedCommitsResponse) Reset()         { *m = NamedCommitsResponse{} }
func (m *NamedCommitsResponse) String() string { return proto.CompactTextString(m) }
func (*NamedCommitsResponse) ProtoMessage()    {}
func (*NamedCommitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_0518ff3e483ebad8, []int{1}
}
func (m *NamedCommitsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedCommitsResponse.Unmarshal(m, b)
}
func (m *NamedCommitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedCommitsResponse.Marshal(b, m, deterministic)
}
func (dst *NamedCommitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedCommitsResponse.Merge(dst, src)
}
func (m *NamedCommitsResponse) XXX_Size() int {
	return xxx_messageInfo_NamedCommitsResponse.Size(m)
}
func (m *NamedCommitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedCommitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NamedCommitsResponse proto.InternalMessageInfo

func (m *NamedCommitsResponse) GetCommits() []*NamedCommit {
	if m != nil {
		return m.Commits
	}
	return nil
}

type NamedCommit struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Branch               bool     `protobuf:"varint,3,opt,name=branch" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedCommit) Reset()         { *m = NamedCommit{} }
func (m *NamedCommit) String() string { return proto.CompactTextString(m) }
func (*NamedCommit) ProtoMessage()    {}
func (*NamedCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_0518ff3e483ebad8, []int{2}
}
func (m *NamedCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedCommit.Unmarshal(m, b)
}
func (m *NamedCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedCommit.Marshal(b, m, deterministic)
}
func (dst *NamedCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedCommit.Merge(dst, src)
}
func (m *NamedCommit) XXX_Size() int {
	return xxx_messageInfo_NamedCommit.Size(m)
}
func (m *NamedCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedCommit.DiscardUnknown(m)
}

var xxx_messageInfo_NamedCommit proto.InternalMessageInfo

func (m *NamedCommit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedCommit) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *NamedCommit) GetBranch() bool {
	if m != nil {
		return m.Branch
	}
	return false
}

type RepositoryExistRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepositoryExistRequest) Reset()         { *m = RepositoryExistRequest{} }
func (m *RepositoryExistRequest) String() string { return proto.CompactTextString(m) }
func (*RepositoryExistRequest) ProtoMessage()    {}
func (*RepositoryExistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_0518ff3e483ebad8, []int{3}
}
func (m *RepositoryExistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryExistRequest.Unmarshal(m, b)
}
func (m *RepositoryExistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryExistRequest.Marshal(b, m, deterministic)
}
func (dst *RepositoryExistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryExistRequest.Merge(dst, src)
}
func (m *RepositoryExistRequest) XXX_Size() int {
	return xxx_messageInfo_RepositoryExistRequest.Size(m)
}
func (m *RepositoryExistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryExistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryExistRequest proto.InternalMessageInfo

func (m *RepositoryExistRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RepositoryExistRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *RepositoryExistRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RepositoryExistResponse struct {
	Exist                bool     `protobuf:"varint,1,opt,name=exist" json:"exist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepositoryExistResponse) Reset()         { *m = RepositoryExistResponse{} }
func (m *RepositoryExistResponse) String() string { return proto.CompactTextString(m) }
func (*RepositoryExistResponse) ProtoMessage()    {}
func (*RepositoryExistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_0518ff3e483ebad8, []int{4}
}
func (m *RepositoryExistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryExistResponse.Unmarshal(m, b)
}
func (m *RepositoryExistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryExistResponse.Marshal(b, m, deterministic)
}
func (dst *RepositoryExistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryExistResponse.Merge(dst, src)
}
func (m *RepositoryExistResponse) XXX_Size() int {
	return xxx_messageInfo_RepositoryExistResponse.Size(m)
}
func (m *RepositoryExistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryExistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryExistResponse proto.InternalMessageInfo

func (m *RepositoryExistResponse) GetExist() bool {
	if m != nil {
		return m.Exist
	}
	return false
}

type DirectoryRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectoryRequest) Reset()         { *m = DirectoryRequest{} }
func (m *DirectoryRequest) String() string { return proto.CompactTextString(m) }
func (*DirectoryRequest) ProtoMessage()    {}
func (*DirectoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_0518ff3e483ebad8, []int{5}
}
func (m *DirectoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryRequest.Unmarshal(m, b)
}
func (m *DirectoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryRequest.Marshal(b, m, deterministic)
}
func (dst *DirectoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryRequest.Merge(dst, src)
}
func (m *DirectoryRequest) XXX_Size() int {
	return xxx_messageInfo_DirectoryRequest.Size(m)
}
func (m *DirectoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryRequest proto.InternalMessageInfo

func (m *DirectoryRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DirectoryRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *DirectoryRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type DirectoryResponse struct {
	Entries              []*DirectoryEntry `protobuf:"bytes,3,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DirectoryResponse) Reset()         { *m = DirectoryResponse{} }
func (m *DirectoryResponse) String() string { return proto.CompactTextString(m) }
func (*DirectoryResponse) ProtoMessage()    {}
func (*DirectoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_0518ff3e483ebad8, []int{6}
}
func (m *DirectoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryResponse.Unmarshal(m, b)
}
func (m *DirectoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryResponse.Marshal(b, m, deterministic)
}
func (dst *DirectoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryResponse.Merge(dst, src)
}
func (m *DirectoryResponse) XXX_Size() int {
	return xxx_messageInfo_DirectoryResponse.Size(m)
}
func (m *DirectoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryResponse proto.InternalMessageInfo

func (m *DirectoryResponse) GetEntries() []*DirectoryEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type DirectoryEntry struct {
	File                 string   `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Dir                  bool     `protobuf:"varint,2,opt,name=dir" json:"dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectoryEntry) Reset()         { *m = DirectoryEntry{} }
func (m *DirectoryEntry) String() string { return proto.CompactTextString(m) }
func (*DirectoryEntry) ProtoMessage()    {}
func (*DirectoryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_0518ff3e483ebad8, []int{7}
}
func (m *DirectoryEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryEntry.Unmarshal(m, b)
}
func (m *DirectoryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryEntry.Marshal(b, m, deterministic)
}
func (dst *DirectoryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryEntry.Merge(dst, src)
}
func (m *DirectoryEntry) XXX_Size() int {
	return xxx_messageInfo_DirectoryEntry.Size(m)
}
func (m *DirectoryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryEntry proto.InternalMessageInfo

func (m *DirectoryEntry) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *DirectoryEntry) GetDir() bool {
	if m != nil {
		return m.Dir
	}
	return false
}

type BlobRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlobRequest) Reset()         { *m = BlobRequest{} }
func (m *BlobRequest) String() string { return proto.CompactTextString(m) }
func (*BlobRequest) ProtoMessage()    {}
func (*BlobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_0518ff3e483ebad8, []int{8}
}
func (m *BlobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobRequest.Unmarshal(m, b)
}
func (m *BlobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobRequest.Marshal(b, m, deterministic)
}
func (dst *BlobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobRequest.Merge(dst, src)
}
func (m *BlobRequest) XXX_Size() int {
	return xxx_messageInfo_BlobRequest.Size(m)
}
func (m *BlobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlobRequest proto.InternalMessageInfo

func (m *BlobRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *BlobRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BlobRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type BlobResponse struct {
	Content              string   `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	Plain                bool     `protobuf:"varint,4,opt,name=plain" json:"plain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlobResponse) Reset()         { *m = BlobResponse{} }
func (m *BlobResponse) String() string { return proto.CompactTextString(m) }
func (*BlobResponse) ProtoMessage()    {}
func (*BlobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_0518ff3e483ebad8, []int{9}
}
func (m *BlobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobResponse.Unmarshal(m, b)
}
func (m *BlobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobResponse.Marshal(b, m, deterministic)
}
func (dst *BlobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobResponse.Merge(dst, src)
}
func (m *BlobResponse) XXX_Size() int {
	return xxx_messageInfo_BlobResponse.Size(m)
}
func (m *BlobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlobResponse proto.InternalMessageInfo

func (m *BlobResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *BlobResponse) GetPlain() bool {
	if m != nil {
		return m.Plain
	}
	return false
}

func init() {
	proto.RegisterType((*NamedCommitsRequest)(nil), "repository.NamedCommitsRequest")
	proto.RegisterType((*NamedCommitsResponse)(nil), "repository.NamedCommitsResponse")
	proto.RegisterType((*NamedCommit)(nil), "repository.NamedCommit")
	proto.RegisterType((*RepositoryExistRequest)(nil), "repository.RepositoryExistRequest")
	proto.RegisterType((*RepositoryExistResponse)(nil), "repository.RepositoryExistResponse")
	proto.RegisterType((*DirectoryRequest)(nil), "repository.DirectoryRequest")
	proto.RegisterType((*DirectoryResponse)(nil), "repository.DirectoryResponse")
	proto.RegisterType((*DirectoryEntry)(nil), "repository.DirectoryEntry")
	proto.RegisterType((*BlobRequest)(nil), "repository.BlobRequest")
	proto.RegisterType((*BlobResponse)(nil), "repository.BlobResponse")
	proto.RegisterEnum("repository.RepositoryErrorCode", RepositoryErrorCode_name, RepositoryErrorCode_value)
}

func init() { proto.RegisterFile("repository.proto", fileDescriptor_repository_0518ff3e483ebad8) }

var fileDescriptor_repository_0518ff3e483ebad8 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xa5, 0x9b, 0xd2, 0x76, 0xa7, 0x11, 0x4a, 0x67, 0x57, 0xdb, 0xa8, 0x02, 0x51, 0x99, 0x03,
	0x15, 0x87, 0x45, 0x2c, 0x08, 0x89, 0x0b, 0x07, 0x96, 0x05, 0x2a, 0xc1, 0x4a, 0xb8, 0x57, 0x2e,
	0x69, 0x6a, 0x54, 0x4b, 0xad, 0x1d, 0x6c, 0x17, 0xd1, 0x5f, 0xe9, 0xdf, 0x00, 0x27, 0xfe, 0x0a,
	0x39, 0xb1, 0x53, 0x97, 0x6d, 0x91, 0x10, 0xb7, 0xf1, 0xf8, 0xcd, 0x7b, 0x99, 0xe7, 0x99, 0x40,
	0xa2, 0x58, 0x21, 0x35, 0x37, 0x52, 0xad, 0xcf, 0x0b, 0x25, 0x8d, 0x44, 0xd8, 0x66, 0xc8, 0x43,
	0x38, 0xb9, 0xce, 0x96, 0x6c, 0x76, 0x29, 0x97, 0x4b, 0x6e, 0x34, 0x65, 0x5f, 0x56, 0x4c, 0x1b,
	0x4c, 0x20, 0x5a, 0xa9, 0x45, 0xda, 0x18, 0x36, 0x46, 0xc7, 0xd4, 0x86, 0x64, 0x0c, 0xa7, 0xbb,
	0x40, 0x5d, 0x48, 0xa1, 0x19, 0x3e, 0x81, 0x76, 0x5e, 0xa5, 0xd2, 0x68, 0x18, 0x8d, 0xba, 0x17,
	0xfd, 0xf3, 0x40, 0x30, 0x28, 0xa1, 0x1e, 0x47, 0x3e, 0x40, 0x37, 0xc8, 0x23, 0x42, 0x53, 0x64,
	0x4b, 0xe6, 0xc4, 0xca, 0xd8, 0xe6, 0xe6, 0x99, 0x9e, 0xa7, 0x47, 0x55, 0xce, 0xc6, 0x78, 0x06,
	0xad, 0xa9, 0xca, 0x44, 0x3e, 0x4f, 0xa3, 0x61, 0x63, 0xd4, 0xa1, 0xee, 0x44, 0x28, 0x9c, 0xd1,
	0x5a, 0xf1, 0xea, 0x1b, 0xd7, 0xe6, 0x60, 0x17, 0x7b, 0x79, 0xbd, 0x7e, 0xb4, 0xd5, 0x27, 0x8f,
	0xa1, 0x7f, 0x83, 0xd3, 0x35, 0x7c, 0x0a, 0xb7, 0x99, 0x4d, 0x94, 0xb4, 0x1d, 0x5a, 0x1d, 0xc8,
	0x7b, 0x48, 0x5e, 0x73, 0xc5, 0x72, 0x8b, 0xff, 0x67, 0xf9, 0x22, 0x33, 0x73, 0x2f, 0x6f, 0x63,
	0x32, 0x86, 0x5e, 0xc0, 0xe6, 0x84, 0x9f, 0x41, 0x9b, 0x09, 0xa3, 0x38, 0xf3, 0x4e, 0x0f, 0x42,
	0xa7, 0x6b, 0xfc, 0x95, 0x30, 0x6a, 0x4d, 0x3d, 0x94, 0x3c, 0x87, 0x3b, 0xbb, 0x57, 0x56, 0xf0,
	0x33, 0x5f, 0xd4, 0x7e, 0xdb, 0xd8, 0x7e, 0xea, 0x8c, 0xab, 0xf2, 0xbb, 0x3a, 0xd4, 0x86, 0xe4,
	0x2d, 0x74, 0x5f, 0x2d, 0xe4, 0xf4, 0xff, 0x7b, 0x79, 0x09, 0x71, 0x45, 0xe4, 0xda, 0x48, 0xed,
	0xc0, 0x08, 0xc3, 0x84, 0x71, 0x30, 0x7f, 0xb4, 0xce, 0x16, 0x8b, 0x8c, 0x8b, 0xb4, 0x59, 0x39,
	0x5b, 0x1e, 0x1e, 0xe5, 0x70, 0x12, 0x3c, 0x85, 0x52, 0x52, 0x5d, 0xca, 0x19, 0xc3, 0x2e, 0xb4,
	0x27, 0xab, 0x3c, 0x67, 0x5a, 0x27, 0xb7, 0x30, 0x86, 0xd6, 0x58, 0x4c, 0xd6, 0x22, 0x4f, 0xbe,
	0x6f, 0x62, 0x4c, 0x01, 0xb7, 0x15, 0xd7, 0xd2, 0xbc, 0x91, 0x2b, 0x31, 0x4b, 0x7e, 0x6c, 0x62,
	0xec, 0x07, 0xbe, 0xd6, 0x17, 0x3f, 0x37, 0xf1, 0xc5, 0xaf, 0x23, 0xe8, 0x6d, 0x6b, 0x26, 0x4c,
	0x7d, 0xe5, 0x39, 0xc3, 0x4f, 0xd0, 0x1b, 0xeb, 0x3f, 0xe6, 0x00, 0x49, 0xe8, 0xfa, 0xfe, 0xc1,
	0x1b, 0x3c, 0xf8, 0x2b, 0xc6, 0x19, 0xf1, 0x11, 0xe2, 0x70, 0xa3, 0xf0, 0xfe, 0x81, 0xc5, 0xf1,
	0x4b, 0x39, 0x18, 0x1e, 0x06, 0x38, 0xca, 0x77, 0x70, 0x5c, 0xf7, 0x87, 0x77, 0xf7, 0x8e, 0x87,
	0x27, 0xbb, 0x77, 0xe0, 0xd6, 0x31, 0xbd, 0x80, 0xa6, 0x7d, 0x35, 0xdc, 0xd9, 0xe6, 0x60, 0x20,
	0x06, 0xe9, 0xcd, 0x8b, 0xaa, 0x74, 0xda, 0x2a, 0xff, 0x32, 0x4f, 0x7f, 0x07, 0x00, 0x00, 0xff,
	0xff, 0xbb, 0xc8, 0x48, 0x40, 0x79, 0x04, 0x00, 0x00,
}
