// Code generated by protoc-gen-go. DO NOT EDIT.
// source: project.proto

package project

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_Success             ErrorCode = 0
	ErrorCode_RepositoryNotExist  ErrorCode = 400001
	ErrorCode_ProjectExist        ErrorCode = 400002
	ErrorCode_IndexProjectFailure ErrorCode = 400003
)

var ErrorCode_name = map[int32]string{
	0:      "Success",
	400001: "RepositoryNotExist",
	400002: "ProjectExist",
	400003: "IndexProjectFailure",
}
var ErrorCode_value = map[string]int32{
	"Success":             0,
	"RepositoryNotExist":  400001,
	"ProjectExist":        400002,
	"IndexProjectFailure": 400003,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{0}
}

type NewProjectRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash" json:"hash,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Branch               bool     `protobuf:"varint,5,opt,name=branch" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewProjectRequest) Reset()         { *m = NewProjectRequest{} }
func (m *NewProjectRequest) String() string { return proto.CompactTextString(m) }
func (*NewProjectRequest) ProtoMessage()    {}
func (*NewProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{0}
}
func (m *NewProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewProjectRequest.Unmarshal(m, b)
}
func (m *NewProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewProjectRequest.Marshal(b, m, deterministic)
}
func (dst *NewProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewProjectRequest.Merge(dst, src)
}
func (m *NewProjectRequest) XXX_Size() int {
	return xxx_messageInfo_NewProjectRequest.Size(m)
}
func (m *NewProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewProjectRequest proto.InternalMessageInfo

func (m *NewProjectRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *NewProjectRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *NewProjectRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *NewProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewProjectRequest) GetBranch() bool {
	if m != nil {
		return m.Branch
	}
	return false
}

type NewProjectResponse struct {
	Id                   string   `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewProjectResponse) Reset()         { *m = NewProjectResponse{} }
func (m *NewProjectResponse) String() string { return proto.CompactTextString(m) }
func (*NewProjectResponse) ProtoMessage()    {}
func (*NewProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{1}
}
func (m *NewProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewProjectResponse.Unmarshal(m, b)
}
func (m *NewProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewProjectResponse.Marshal(b, m, deterministic)
}
func (dst *NewProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewProjectResponse.Merge(dst, src)
}
func (m *NewProjectResponse) XXX_Size() int {
	return xxx_messageInfo_NewProjectResponse.Size(m)
}
func (m *NewProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewProjectResponse proto.InternalMessageInfo

func (m *NewProjectResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProjectInfoRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	OwnerUid             string   `protobuf:"bytes,2,opt,name=ownerUid" json:"ownerUid,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectInfoRequest) Reset()         { *m = ProjectInfoRequest{} }
func (m *ProjectInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectInfoRequest) ProtoMessage()    {}
func (*ProjectInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{2}
}
func (m *ProjectInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectInfoRequest.Unmarshal(m, b)
}
func (m *ProjectInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectInfoRequest.Marshal(b, m, deterministic)
}
func (dst *ProjectInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectInfoRequest.Merge(dst, src)
}
func (m *ProjectInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectInfoRequest.Size(m)
}
func (m *ProjectInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectInfoRequest proto.InternalMessageInfo

func (m *ProjectInfoRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ProjectInfoRequest) GetOwnerUid() string {
	if m != nil {
		return m.OwnerUid
	}
	return ""
}

func (m *ProjectInfoRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ProjectInfoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProjectInfoResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Branch               bool     `protobuf:"varint,3,opt,name=branch" json:"branch,omitempty"`
	CanAnnotate          bool     `protobuf:"varint,4,opt,name=canAnnotate" json:"canAnnotate,omitempty"`
	Indexed              bool     `protobuf:"varint,5,opt,name=indexed" json:"indexed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectInfoResponse) Reset()         { *m = ProjectInfoResponse{} }
func (m *ProjectInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectInfoResponse) ProtoMessage()    {}
func (*ProjectInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{3}
}
func (m *ProjectInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectInfoResponse.Unmarshal(m, b)
}
func (m *ProjectInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectInfoResponse.Marshal(b, m, deterministic)
}
func (dst *ProjectInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectInfoResponse.Merge(dst, src)
}
func (m *ProjectInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectInfoResponse.Size(m)
}
func (m *ProjectInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectInfoResponse proto.InternalMessageInfo

func (m *ProjectInfoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProjectInfoResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *ProjectInfoResponse) GetBranch() bool {
	if m != nil {
		return m.Branch
	}
	return false
}

func (m *ProjectInfoResponse) GetCanAnnotate() bool {
	if m != nil {
		return m.CanAnnotate
	}
	return false
}

func (m *ProjectInfoResponse) GetIndexed() bool {
	if m != nil {
		return m.Indexed
	}
	return false
}

type AddAnnotationRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid" json:"pid,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid" json:"uid,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	File                 string   `protobuf:"bytes,4,opt,name=file" json:"file,omitempty"`
	LineNumber           int32    `protobuf:"varint,5,opt,name=lineNumber" json:"lineNumber,omitempty"`
	Annotation           string   `protobuf:"bytes,6,opt,name=annotation" json:"annotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAnnotationRequest) Reset()         { *m = AddAnnotationRequest{} }
func (m *AddAnnotationRequest) String() string { return proto.CompactTextString(m) }
func (*AddAnnotationRequest) ProtoMessage()    {}
func (*AddAnnotationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{4}
}
func (m *AddAnnotationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAnnotationRequest.Unmarshal(m, b)
}
func (m *AddAnnotationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAnnotationRequest.Marshal(b, m, deterministic)
}
func (dst *AddAnnotationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAnnotationRequest.Merge(dst, src)
}
func (m *AddAnnotationRequest) XXX_Size() int {
	return xxx_messageInfo_AddAnnotationRequest.Size(m)
}
func (m *AddAnnotationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAnnotationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAnnotationRequest proto.InternalMessageInfo

func (m *AddAnnotationRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *AddAnnotationRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AddAnnotationRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AddAnnotationRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *AddAnnotationRequest) GetLineNumber() int32 {
	if m != nil {
		return m.LineNumber
	}
	return 0
}

func (m *AddAnnotationRequest) GetAnnotation() string {
	if m != nil {
		return m.Annotation
	}
	return ""
}

type AddAnnotationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAnnotationResponse) Reset()         { *m = AddAnnotationResponse{} }
func (m *AddAnnotationResponse) String() string { return proto.CompactTextString(m) }
func (*AddAnnotationResponse) ProtoMessage()    {}
func (*AddAnnotationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{5}
}
func (m *AddAnnotationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAnnotationResponse.Unmarshal(m, b)
}
func (m *AddAnnotationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAnnotationResponse.Marshal(b, m, deterministic)
}
func (dst *AddAnnotationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAnnotationResponse.Merge(dst, src)
}
func (m *AddAnnotationResponse) XXX_Size() int {
	return xxx_messageInfo_AddAnnotationResponse.Size(m)
}
func (m *AddAnnotationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAnnotationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAnnotationResponse proto.InternalMessageInfo

type GetAnnotationLinesRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid" json:"pid,omitempty"`
	File                 string   `protobuf:"bytes,2,opt,name=file" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnnotationLinesRequest) Reset()         { *m = GetAnnotationLinesRequest{} }
func (m *GetAnnotationLinesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAnnotationLinesRequest) ProtoMessage()    {}
func (*GetAnnotationLinesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{6}
}
func (m *GetAnnotationLinesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnnotationLinesRequest.Unmarshal(m, b)
}
func (m *GetAnnotationLinesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnnotationLinesRequest.Marshal(b, m, deterministic)
}
func (dst *GetAnnotationLinesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnnotationLinesRequest.Merge(dst, src)
}
func (m *GetAnnotationLinesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAnnotationLinesRequest.Size(m)
}
func (m *GetAnnotationLinesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnnotationLinesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnnotationLinesRequest proto.InternalMessageInfo

func (m *GetAnnotationLinesRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *GetAnnotationLinesRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

type GetAnnotationLinesResponse struct {
	Lines                []int32  `protobuf:"varint,1,rep,packed,name=lines" json:"lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnnotationLinesResponse) Reset()         { *m = GetAnnotationLinesResponse{} }
func (m *GetAnnotationLinesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAnnotationLinesResponse) ProtoMessage()    {}
func (*GetAnnotationLinesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{7}
}
func (m *GetAnnotationLinesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnnotationLinesResponse.Unmarshal(m, b)
}
func (m *GetAnnotationLinesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnnotationLinesResponse.Marshal(b, m, deterministic)
}
func (dst *GetAnnotationLinesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnnotationLinesResponse.Merge(dst, src)
}
func (m *GetAnnotationLinesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAnnotationLinesResponse.Size(m)
}
func (m *GetAnnotationLinesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnnotationLinesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnnotationLinesResponse proto.InternalMessageInfo

func (m *GetAnnotationLinesResponse) GetLines() []int32 {
	if m != nil {
		return m.Lines
	}
	return nil
}

type GetAnnotationsRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid" json:"pid,omitempty"`
	File                 string   `protobuf:"bytes,2,opt,name=file" json:"file,omitempty"`
	LineNumber           int32    `protobuf:"varint,3,opt,name=lineNumber" json:"lineNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnnotationsRequest) Reset()         { *m = GetAnnotationsRequest{} }
func (m *GetAnnotationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAnnotationsRequest) ProtoMessage()    {}
func (*GetAnnotationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{8}
}
func (m *GetAnnotationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnnotationsRequest.Unmarshal(m, b)
}
func (m *GetAnnotationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnnotationsRequest.Marshal(b, m, deterministic)
}
func (dst *GetAnnotationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnnotationsRequest.Merge(dst, src)
}
func (m *GetAnnotationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAnnotationsRequest.Size(m)
}
func (m *GetAnnotationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnnotationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnnotationsRequest proto.InternalMessageInfo

func (m *GetAnnotationsRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *GetAnnotationsRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *GetAnnotationsRequest) GetLineNumber() int32 {
	if m != nil {
		return m.LineNumber
	}
	return 0
}

type GetAnnotationsResponse struct {
	Records              []*AnnotationRecord `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAnnotationsResponse) Reset()         { *m = GetAnnotationsResponse{} }
func (m *GetAnnotationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAnnotationsResponse) ProtoMessage()    {}
func (*GetAnnotationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{9}
}
func (m *GetAnnotationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnnotationsResponse.Unmarshal(m, b)
}
func (m *GetAnnotationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnnotationsResponse.Marshal(b, m, deterministic)
}
func (dst *GetAnnotationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnnotationsResponse.Merge(dst, src)
}
func (m *GetAnnotationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAnnotationsResponse.Size(m)
}
func (m *GetAnnotationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnnotationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnnotationsResponse proto.InternalMessageInfo

func (m *GetAnnotationsResponse) GetRecords() []*AnnotationRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type AnnotationRecord struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Annotation           string   `protobuf:"bytes,3,opt,name=annotation" json:"annotation,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=createdAt" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnotationRecord) Reset()         { *m = AnnotationRecord{} }
func (m *AnnotationRecord) String() string { return proto.CompactTextString(m) }
func (*AnnotationRecord) ProtoMessage()    {}
func (*AnnotationRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{10}
}
func (m *AnnotationRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnotationRecord.Unmarshal(m, b)
}
func (m *AnnotationRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnotationRecord.Marshal(b, m, deterministic)
}
func (dst *AnnotationRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnotationRecord.Merge(dst, src)
}
func (m *AnnotationRecord) XXX_Size() int {
	return xxx_messageInfo_AnnotationRecord.Size(m)
}
func (m *AnnotationRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnotationRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AnnotationRecord proto.InternalMessageInfo

func (m *AnnotationRecord) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AnnotationRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnnotationRecord) GetAnnotation() string {
	if m != nil {
		return m.Annotation
	}
	return ""
}

func (m *AnnotationRecord) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type GetLatestAnnotationsRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid" json:"pid,omitempty"`
	Parent               string   `protobuf:"bytes,2,opt,name=parent" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLatestAnnotationsRequest) Reset()         { *m = GetLatestAnnotationsRequest{} }
func (m *GetLatestAnnotationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestAnnotationsRequest) ProtoMessage()    {}
func (*GetLatestAnnotationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{11}
}
func (m *GetLatestAnnotationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestAnnotationsRequest.Unmarshal(m, b)
}
func (m *GetLatestAnnotationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestAnnotationsRequest.Marshal(b, m, deterministic)
}
func (dst *GetLatestAnnotationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestAnnotationsRequest.Merge(dst, src)
}
func (m *GetLatestAnnotationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetLatestAnnotationsRequest.Size(m)
}
func (m *GetLatestAnnotationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestAnnotationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestAnnotationsRequest proto.InternalMessageInfo

func (m *GetLatestAnnotationsRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *GetLatestAnnotationsRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type GetLatestAnnotationsResponse struct {
	Annotations          []*LatestAnnotation `protobuf:"bytes,1,rep,name=annotations" json:"annotations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetLatestAnnotationsResponse) Reset()         { *m = GetLatestAnnotationsResponse{} }
func (m *GetLatestAnnotationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetLatestAnnotationsResponse) ProtoMessage()    {}
func (*GetLatestAnnotationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{12}
}
func (m *GetLatestAnnotationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestAnnotationsResponse.Unmarshal(m, b)
}
func (m *GetLatestAnnotationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestAnnotationsResponse.Marshal(b, m, deterministic)
}
func (dst *GetLatestAnnotationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestAnnotationsResponse.Merge(dst, src)
}
func (m *GetLatestAnnotationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetLatestAnnotationsResponse.Size(m)
}
func (m *GetLatestAnnotationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestAnnotationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestAnnotationsResponse proto.InternalMessageInfo

func (m *GetLatestAnnotationsResponse) GetAnnotations() []*LatestAnnotation {
	if m != nil {
		return m.Annotations
	}
	return nil
}

type LatestAnnotation struct {
	File                 string   `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	LineNumber           int32    `protobuf:"varint,2,opt,name=lineNumber" json:"lineNumber,omitempty"`
	Brief                string   `protobuf:"bytes,3,opt,name=brief" json:"brief,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Sub                  string   `protobuf:"bytes,5,opt,name=sub" json:"sub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatestAnnotation) Reset()         { *m = LatestAnnotation{} }
func (m *LatestAnnotation) String() string { return proto.CompactTextString(m) }
func (*LatestAnnotation) ProtoMessage()    {}
func (*LatestAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{13}
}
func (m *LatestAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestAnnotation.Unmarshal(m, b)
}
func (m *LatestAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestAnnotation.Marshal(b, m, deterministic)
}
func (dst *LatestAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestAnnotation.Merge(dst, src)
}
func (m *LatestAnnotation) XXX_Size() int {
	return xxx_messageInfo_LatestAnnotation.Size(m)
}
func (m *LatestAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_LatestAnnotation proto.InternalMessageInfo

func (m *LatestAnnotation) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *LatestAnnotation) GetLineNumber() int32 {
	if m != nil {
		return m.LineNumber
	}
	return 0
}

func (m *LatestAnnotation) GetBrief() string {
	if m != nil {
		return m.Brief
	}
	return ""
}

func (m *LatestAnnotation) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LatestAnnotation) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

type ListProjectsRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectsRequest) Reset()         { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()    {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{14}
}
func (m *ListProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsRequest.Unmarshal(m, b)
}
func (m *ListProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsRequest.Marshal(b, m, deterministic)
}
func (dst *ListProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsRequest.Merge(dst, src)
}
func (m *ListProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectsRequest.Size(m)
}
func (m *ListProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsRequest proto.InternalMessageInfo

func (m *ListProjectsRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type ListProjectsResponse struct {
	Projects             []*ProjectInfo `protobuf:"bytes,1,rep,name=projects" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListProjectsResponse) Reset()         { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()    {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{15}
}
func (m *ListProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsResponse.Unmarshal(m, b)
}
func (m *ListProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsResponse.Marshal(b, m, deterministic)
}
func (dst *ListProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsResponse.Merge(dst, src)
}
func (m *ListProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectsResponse.Size(m)
}
func (m *ListProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsResponse proto.InternalMessageInfo

func (m *ListProjectsResponse) GetProjects() []*ProjectInfo {
	if m != nil {
		return m.Projects
	}
	return nil
}

type ProjectInfo struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash" json:"hash,omitempty"`
	Branch               bool     `protobuf:"varint,4,opt,name=branch" json:"branch,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=createdAt" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectInfo) Reset()         { *m = ProjectInfo{} }
func (m *ProjectInfo) String() string { return proto.CompactTextString(m) }
func (*ProjectInfo) ProtoMessage()    {}
func (*ProjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_19ccf6b0d5f9ff9e, []int{16}
}
func (m *ProjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectInfo.Unmarshal(m, b)
}
func (m *ProjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectInfo.Marshal(b, m, deterministic)
}
func (dst *ProjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectInfo.Merge(dst, src)
}
func (m *ProjectInfo) XXX_Size() int {
	return xxx_messageInfo_ProjectInfo.Size(m)
}
func (m *ProjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectInfo proto.InternalMessageInfo

func (m *ProjectInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ProjectInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProjectInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *ProjectInfo) GetBranch() bool {
	if m != nil {
		return m.Branch
	}
	return false
}

func (m *ProjectInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*NewProjectRequest)(nil), "project.NewProjectRequest")
	proto.RegisterType((*NewProjectResponse)(nil), "project.NewProjectResponse")
	proto.RegisterType((*ProjectInfoRequest)(nil), "project.ProjectInfoRequest")
	proto.RegisterType((*ProjectInfoResponse)(nil), "project.ProjectInfoResponse")
	proto.RegisterType((*AddAnnotationRequest)(nil), "project.AddAnnotationRequest")
	proto.RegisterType((*AddAnnotationResponse)(nil), "project.AddAnnotationResponse")
	proto.RegisterType((*GetAnnotationLinesRequest)(nil), "project.GetAnnotationLinesRequest")
	proto.RegisterType((*GetAnnotationLinesResponse)(nil), "project.GetAnnotationLinesResponse")
	proto.RegisterType((*GetAnnotationsRequest)(nil), "project.GetAnnotationsRequest")
	proto.RegisterType((*GetAnnotationsResponse)(nil), "project.GetAnnotationsResponse")
	proto.RegisterType((*AnnotationRecord)(nil), "project.AnnotationRecord")
	proto.RegisterType((*GetLatestAnnotationsRequest)(nil), "project.GetLatestAnnotationsRequest")
	proto.RegisterType((*GetLatestAnnotationsResponse)(nil), "project.GetLatestAnnotationsResponse")
	proto.RegisterType((*LatestAnnotation)(nil), "project.LatestAnnotation")
	proto.RegisterType((*ListProjectsRequest)(nil), "project.ListProjectsRequest")
	proto.RegisterType((*ListProjectsResponse)(nil), "project.ListProjectsResponse")
	proto.RegisterType((*ProjectInfo)(nil), "project.ProjectInfo")
	proto.RegisterEnum("project.ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("project.proto", fileDescriptor_project_19ccf6b0d5f9ff9e) }

var fileDescriptor_project_19ccf6b0d5f9ff9e = []byte{
	// 776 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xbe, 0x8e, 0xf3, 0x7b, 0xd2, 0x56, 0xb9, 0xd3, 0xb4, 0xd7, 0x75, 0x7b, 0x7b, 0xa3, 0xb9,
	0x45, 0x54, 0x2c, 0x2a, 0xd4, 0x2e, 0x59, 0x45, 0xa8, 0xb4, 0x15, 0x25, 0x02, 0x23, 0x56, 0xa8,
	0x0b, 0xc7, 0x9e, 0x2a, 0x83, 0x12, 0x8f, 0x99, 0x99, 0xd0, 0xb2, 0x60, 0x01, 0x6c, 0xe1, 0x1d,
	0x78, 0x89, 0xbe, 0x06, 0xcf, 0x84, 0x6c, 0x8f, 0xed, 0xb1, 0x63, 0xf3, 0xb3, 0x9b, 0xf3, 0x33,
	0x67, 0xbe, 0xf3, 0x9d, 0xe3, 0x2f, 0x81, 0xf5, 0x90, 0xb3, 0x37, 0xc4, 0x93, 0x47, 0x21, 0x67,
	0x92, 0xa1, 0x8e, 0x32, 0xf1, 0x0d, 0xfc, 0x3d, 0x21, 0x37, 0xcf, 0x13, 0xcb, 0x21, 0x6f, 0x97,
	0x44, 0x48, 0x34, 0x00, 0x73, 0x49, 0x7d, 0xcb, 0x18, 0x19, 0x87, 0x3d, 0x27, 0x3a, 0xc6, 0x1e,
	0x3e, 0xb7, 0x1a, 0xca, 0xc3, 0xe7, 0x08, 0x41, 0x73, 0xe6, 0x8a, 0x99, 0x65, 0xc6, 0xae, 0xf8,
	0x1c, 0xf9, 0x02, 0x77, 0x41, 0xac, 0x66, 0xe2, 0x8b, 0xce, 0x68, 0x1b, 0xda, 0x53, 0xee, 0x06,
	0xde, 0xcc, 0x6a, 0x8d, 0x8c, 0xc3, 0xae, 0xa3, 0x2c, 0x7c, 0x00, 0x48, 0x7f, 0x58, 0x84, 0x2c,
	0x10, 0x04, 0x6d, 0x40, 0x83, 0xfa, 0xaa, 0x66, 0x83, 0xfa, 0x78, 0x06, 0x48, 0xa5, 0x5c, 0x04,
	0xd7, 0xac, 0x1e, 0x9f, 0x0d, 0x5d, 0x76, 0x13, 0x10, 0xfe, 0x8a, 0xfa, 0x0a, 0x64, 0x66, 0xa7,
	0xd8, 0xcd, 0x02, 0xf6, 0x32, 0x4e, 0xfc, 0xd5, 0x80, 0xcd, 0xc2, 0x53, 0x05, 0x44, 0x46, 0x8a,
	0x28, 0xeb, 0xbb, 0xa1, 0xf5, 0x9d, 0xf7, 0x68, 0xea, 0x3d, 0xa2, 0x11, 0xf4, 0x3d, 0x37, 0x18,
	0x07, 0x01, 0x93, 0xae, 0x4c, 0x9e, 0xeb, 0x3a, 0xba, 0x0b, 0x59, 0xd0, 0xa1, 0x81, 0x4f, 0x6e,
	0x89, 0xaf, 0xe8, 0x49, 0x4d, 0xfc, 0xcd, 0x80, 0xe1, 0xd8, 0xf7, 0x55, 0x26, 0x65, 0x81, 0xd6,
	0x7c, 0x98, 0x37, 0x1f, 0xaa, 0x06, 0xb3, 0xbe, 0xf5, 0x71, 0x15, 0x5b, 0xbe, 0xa6, 0xf3, 0xac,
	0xe5, 0xe8, 0x8c, 0xf6, 0x01, 0xe6, 0x34, 0x20, 0x93, 0xe5, 0x62, 0x4a, 0x78, 0xfc, 0x7e, 0xcb,
	0xd1, 0x3c, 0x51, 0xdc, 0xcd, 0x9e, 0xb7, 0xda, 0xf1, 0x4d, 0xcd, 0x83, 0xff, 0x81, 0xad, 0x12,
	0xc2, 0x84, 0x33, 0x3c, 0x86, 0x9d, 0x33, 0x22, 0xf3, 0xc0, 0x25, 0x0d, 0x88, 0xa8, 0xc7, 0x9f,
	0x62, 0x6b, 0xe4, 0xd8, 0xf0, 0x31, 0xd8, 0x55, 0x25, 0xd4, 0x50, 0x86, 0xd0, 0x8a, 0x70, 0x0a,
	0xcb, 0x18, 0x99, 0x87, 0x2d, 0x27, 0x31, 0xf0, 0x15, 0x6c, 0x15, 0xee, 0xfc, 0xd9, 0x93, 0x25,
	0x3a, 0xcc, 0x32, 0x1d, 0xf8, 0x19, 0x6c, 0x97, 0xcb, 0x2b, 0x38, 0x27, 0xd0, 0xe1, 0xc4, 0x63,
	0xdc, 0x4f, 0x00, 0xf5, 0x8f, 0x77, 0x8e, 0xd2, 0xcf, 0x4d, 0x67, 0x27, 0xca, 0x70, 0xd2, 0x4c,
	0xfc, 0x0e, 0x06, 0xe5, 0x60, 0xc5, 0x62, 0xa7, 0xab, 0xda, 0xd0, 0x3e, 0xa9, 0xe2, 0x5c, 0xcc,
	0xf2, 0x5c, 0xd0, 0x1e, 0xf4, 0x3c, 0x4e, 0x5c, 0x49, 0xfc, 0xb1, 0x8c, 0x07, 0x6e, 0x3a, 0xb9,
	0x03, 0x9f, 0xc1, 0xee, 0x19, 0x91, 0x97, 0xae, 0x24, 0xe2, 0xf7, 0xb8, 0xda, 0x86, 0x76, 0xe8,
	0x72, 0x12, 0x48, 0x05, 0x42, 0x59, 0xf8, 0x35, 0xec, 0x55, 0x17, 0x52, 0xac, 0x3c, 0x82, 0x7e,
	0x0e, 0x6a, 0x95, 0x99, 0xf2, 0x45, 0x47, 0xcf, 0xc6, 0x5f, 0x0c, 0x18, 0x94, 0x33, 0xb2, 0xa9,
	0x19, 0xb5, 0x53, 0x6b, 0xac, 0x2c, 0xf1, 0x10, 0x5a, 0x53, 0x4e, 0xc9, 0xb5, 0xe2, 0x29, 0x31,
	0x22, 0x8a, 0x24, 0x5d, 0x10, 0x21, 0xdd, 0x45, 0x98, 0x52, 0x94, 0x39, 0x22, 0x0e, 0xc4, 0x72,
	0x1a, 0x7f, 0x11, 0x3d, 0x27, 0x3a, 0xe2, 0xfb, 0xb0, 0x79, 0x49, 0x85, 0x54, 0x02, 0x21, 0x6a,
	0x85, 0x08, 0x9f, 0xc3, 0xb0, 0x98, 0xa8, 0xc8, 0x78, 0x08, 0x5d, 0xd5, 0x78, 0xca, 0xc4, 0x30,
	0x63, 0x42, 0x97, 0x9d, 0x2c, 0x0b, 0x7f, 0x80, 0xbe, 0x16, 0x48, 0x3f, 0x69, 0x63, 0x55, 0xc5,
	0xf4, 0xd5, 0xa8, 0x52, 0xe5, 0x5c, 0x9d, 0x9a, 0x05, 0x75, 0x2a, 0xac, 0x49, 0xab, 0xb4, 0x26,
	0x0f, 0x5c, 0xe8, 0x9d, 0x72, 0xce, 0xf8, 0x63, 0xe6, 0x13, 0xd4, 0x87, 0xce, 0xcb, 0xa5, 0xe7,
	0x11, 0x21, 0x06, 0x7f, 0x21, 0x0b, 0x90, 0x43, 0x42, 0x26, 0xa8, 0x64, 0xfc, 0xfd, 0x84, 0xc9,
	0xd3, 0x5b, 0x2a, 0xe4, 0xe0, 0xe3, 0x9d, 0x85, 0x10, 0xac, 0x29, 0xc8, 0x89, 0xef, 0xd3, 0x9d,
	0x85, 0x76, 0x60, 0xf3, 0x22, 0x92, 0x34, 0x15, 0x78, 0xe2, 0xd2, 0xf9, 0x92, 0x93, 0xc1, 0xe7,
	0x3b, 0xeb, 0xf8, 0x7b, 0x13, 0x3a, 0xca, 0x8d, 0x4e, 0x01, 0xf2, 0x9f, 0x03, 0x64, 0x67, 0xdc,
	0xac, 0xfc, 0x38, 0xd9, 0xbb, 0x95, 0x31, 0x45, 0xf3, 0x79, 0x91, 0xb4, 0xdd, 0x4a, 0x8e, 0x55,
	0xa1, 0xbd, 0xea, 0xa0, 0xaa, 0xf4, 0x14, 0xd6, 0xf4, 0x41, 0xa2, 0x3c, 0xbb, 0x62, 0x11, 0xec,
	0x7f, 0x6b, 0xa2, 0xaa, 0xd8, 0x04, 0xd6, 0x0b, 0x4a, 0x89, 0xf2, 0xfc, 0x2a, 0x8d, 0xb7, 0xf7,
	0xeb, 0xc2, 0xaa, 0xde, 0x15, 0xa0, 0x55, 0x75, 0x44, 0x38, 0xbb, 0x55, 0xab, 0xbe, 0xf6, 0xff,
	0x3f, 0xcd, 0x51, 0xe5, 0x5f, 0xc0, 0x46, 0x51, 0xe9, 0xd0, 0x7e, 0xf5, 0xb5, 0xac, 0xec, 0x7f,
	0xb5, 0x71, 0x55, 0xd2, 0x83, 0x61, 0x95, 0x58, 0xa0, 0x03, 0xfd, 0x62, 0x9d, 0x28, 0xd9, 0xf7,
	0x7e, 0x91, 0x95, 0x3c, 0x32, 0x6d, 0xc7, 0x7f, 0x6e, 0x4e, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x26, 0x9c, 0xa0, 0x88, 0xed, 0x08, 0x00, 0x00,
}
