// Code generated by protoc-gen-go. DO NOT EDIT.
// source: index.proto

package index

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_Success       ErrorCode = 0
	ErrorCode_InternalError ErrorCode = 500
	ErrorCode_IndexerBusy   ErrorCode = 500001
	ErrorCode_Indexing      ErrorCode = 500002
)

var ErrorCode_name = map[int32]string{
	0:      "Success",
	500:    "InternalError",
	500001: "IndexerBusy",
	500002: "Indexing",
}
var ErrorCode_value = map[string]int32{
	"Success":       0,
	"InternalError": 500,
	"IndexerBusy":   500001,
	"Indexing":      500002,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_index_6e0745d1d2361d1a, []int{0}
}

type StatusCode int32

const (
	StatusCode_StatusUnIndexed StatusCode = 0
	StatusCode_StatusIndexing  StatusCode = 2
	StatusCode_StatusIndexed   StatusCode = 3
)

var StatusCode_name = map[int32]string{
	0: "StatusUnIndexed",
	2: "StatusIndexing",
	3: "StatusIndexed",
}
var StatusCode_value = map[string]int32{
	"StatusUnIndexed": 0,
	"StatusIndexing":  2,
	"StatusIndexed":   3,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_index_6e0745d1d2361d1a, []int{1}
}

type IndexRepositoryRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexRepositoryRequest) Reset()         { *m = IndexRepositoryRequest{} }
func (m *IndexRepositoryRequest) String() string { return proto.CompactTextString(m) }
func (*IndexRepositoryRequest) ProtoMessage()    {}
func (*IndexRepositoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_6e0745d1d2361d1a, []int{0}
}
func (m *IndexRepositoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexRepositoryRequest.Unmarshal(m, b)
}
func (m *IndexRepositoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexRepositoryRequest.Marshal(b, m, deterministic)
}
func (dst *IndexRepositoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexRepositoryRequest.Merge(dst, src)
}
func (m *IndexRepositoryRequest) XXX_Size() int {
	return xxx_messageInfo_IndexRepositoryRequest.Size(m)
}
func (m *IndexRepositoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexRepositoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexRepositoryRequest proto.InternalMessageInfo

func (m *IndexRepositoryRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *IndexRepositoryRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type IndexRepositoryResponse struct {
	Indexed              bool     `protobuf:"varint,1,opt,name=indexed" json:"indexed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexRepositoryResponse) Reset()         { *m = IndexRepositoryResponse{} }
func (m *IndexRepositoryResponse) String() string { return proto.CompactTextString(m) }
func (*IndexRepositoryResponse) ProtoMessage()    {}
func (*IndexRepositoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_6e0745d1d2361d1a, []int{1}
}
func (m *IndexRepositoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexRepositoryResponse.Unmarshal(m, b)
}
func (m *IndexRepositoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexRepositoryResponse.Marshal(b, m, deterministic)
}
func (dst *IndexRepositoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexRepositoryResponse.Merge(dst, src)
}
func (m *IndexRepositoryResponse) XXX_Size() int {
	return xxx_messageInfo_IndexRepositoryResponse.Size(m)
}
func (m *IndexRepositoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexRepositoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexRepositoryResponse proto.InternalMessageInfo

func (m *IndexRepositoryResponse) GetIndexed() bool {
	if m != nil {
		return m.Indexed
	}
	return false
}

type IndexStatusRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexStatusRequest) Reset()         { *m = IndexStatusRequest{} }
func (m *IndexStatusRequest) String() string { return proto.CompactTextString(m) }
func (*IndexStatusRequest) ProtoMessage()    {}
func (*IndexStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_6e0745d1d2361d1a, []int{2}
}
func (m *IndexStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexStatusRequest.Unmarshal(m, b)
}
func (m *IndexStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexStatusRequest.Marshal(b, m, deterministic)
}
func (dst *IndexStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexStatusRequest.Merge(dst, src)
}
func (m *IndexStatusRequest) XXX_Size() int {
	return xxx_messageInfo_IndexStatusRequest.Size(m)
}
func (m *IndexStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexStatusRequest proto.InternalMessageInfo

func (m *IndexStatusRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *IndexStatusRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type IndexStatusResponse struct {
	Status               StatusCode `protobuf:"varint,3,opt,name=status,enum=index.StatusCode" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IndexStatusResponse) Reset()         { *m = IndexStatusResponse{} }
func (m *IndexStatusResponse) String() string { return proto.CompactTextString(m) }
func (*IndexStatusResponse) ProtoMessage()    {}
func (*IndexStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_6e0745d1d2361d1a, []int{3}
}
func (m *IndexStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexStatusResponse.Unmarshal(m, b)
}
func (m *IndexStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexStatusResponse.Marshal(b, m, deterministic)
}
func (dst *IndexStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexStatusResponse.Merge(dst, src)
}
func (m *IndexStatusResponse) XXX_Size() int {
	return xxx_messageInfo_IndexStatusResponse.Size(m)
}
func (m *IndexStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexStatusResponse proto.InternalMessageInfo

func (m *IndexStatusResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_StatusUnIndexed
}

type SearchSymbolRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchSymbolRequest) Reset()         { *m = SearchSymbolRequest{} }
func (m *SearchSymbolRequest) String() string { return proto.CompactTextString(m) }
func (*SearchSymbolRequest) ProtoMessage()    {}
func (*SearchSymbolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_6e0745d1d2361d1a, []int{4}
}
func (m *SearchSymbolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSymbolRequest.Unmarshal(m, b)
}
func (m *SearchSymbolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSymbolRequest.Marshal(b, m, deterministic)
}
func (dst *SearchSymbolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSymbolRequest.Merge(dst, src)
}
func (m *SearchSymbolRequest) XXX_Size() int {
	return xxx_messageInfo_SearchSymbolRequest.Size(m)
}
func (m *SearchSymbolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSymbolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSymbolRequest proto.InternalMessageInfo

func (m *SearchSymbolRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SearchSymbolRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *SearchSymbolRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type SearchSymbolResponse struct {
	Symbols              []*SymbolResult `protobuf:"bytes,1,rep,name=symbols" json:"symbols,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SearchSymbolResponse) Reset()         { *m = SearchSymbolResponse{} }
func (m *SearchSymbolResponse) String() string { return proto.CompactTextString(m) }
func (*SearchSymbolResponse) ProtoMessage()    {}
func (*SearchSymbolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_6e0745d1d2361d1a, []int{5}
}
func (m *SearchSymbolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSymbolResponse.Unmarshal(m, b)
}
func (m *SearchSymbolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSymbolResponse.Marshal(b, m, deterministic)
}
func (dst *SearchSymbolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSymbolResponse.Merge(dst, src)
}
func (m *SearchSymbolResponse) XXX_Size() int {
	return xxx_messageInfo_SearchSymbolResponse.Size(m)
}
func (m *SearchSymbolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSymbolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSymbolResponse proto.InternalMessageInfo

func (m *SearchSymbolResponse) GetSymbols() []*SymbolResult {
	if m != nil {
		return m.Symbols
	}
	return nil
}

type SymbolResult struct {
	File                 string   `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	LineNumber           int32    `protobuf:"varint,2,opt,name=lineNumber" json:"lineNumber,omitempty"`
	Line                 string   `protobuf:"bytes,3,opt,name=line" json:"line,omitempty"`
	LineBefore           string   `protobuf:"bytes,4,opt,name=lineBefore" json:"lineBefore,omitempty"`
	LineAfter            string   `protobuf:"bytes,5,opt,name=lineAfter" json:"lineAfter,omitempty"`
	Kind                 string   `protobuf:"bytes,6,opt,name=kind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SymbolResult) Reset()         { *m = SymbolResult{} }
func (m *SymbolResult) String() string { return proto.CompactTextString(m) }
func (*SymbolResult) ProtoMessage()    {}
func (*SymbolResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_6e0745d1d2361d1a, []int{6}
}
func (m *SymbolResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SymbolResult.Unmarshal(m, b)
}
func (m *SymbolResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SymbolResult.Marshal(b, m, deterministic)
}
func (dst *SymbolResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SymbolResult.Merge(dst, src)
}
func (m *SymbolResult) XXX_Size() int {
	return xxx_messageInfo_SymbolResult.Size(m)
}
func (m *SymbolResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SymbolResult.DiscardUnknown(m)
}

var xxx_messageInfo_SymbolResult proto.InternalMessageInfo

func (m *SymbolResult) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *SymbolResult) GetLineNumber() int32 {
	if m != nil {
		return m.LineNumber
	}
	return 0
}

func (m *SymbolResult) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *SymbolResult) GetLineBefore() string {
	if m != nil {
		return m.LineBefore
	}
	return ""
}

func (m *SymbolResult) GetLineAfter() string {
	if m != nil {
		return m.LineAfter
	}
	return ""
}

func (m *SymbolResult) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func init() {
	proto.RegisterType((*IndexRepositoryRequest)(nil), "index.IndexRepositoryRequest")
	proto.RegisterType((*IndexRepositoryResponse)(nil), "index.IndexRepositoryResponse")
	proto.RegisterType((*IndexStatusRequest)(nil), "index.IndexStatusRequest")
	proto.RegisterType((*IndexStatusResponse)(nil), "index.IndexStatusResponse")
	proto.RegisterType((*SearchSymbolRequest)(nil), "index.SearchSymbolRequest")
	proto.RegisterType((*SearchSymbolResponse)(nil), "index.SearchSymbolResponse")
	proto.RegisterType((*SymbolResult)(nil), "index.SymbolResult")
	proto.RegisterEnum("index.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("index.StatusCode", StatusCode_name, StatusCode_value)
}

func init() { proto.RegisterFile("index.proto", fileDescriptor_index_6e0745d1d2361d1a) }

var fileDescriptor_index_6e0745d1d2361d1a = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x75, 0x93, 0x34, 0x93, 0x36, 0x75, 0x26, 0xa8, 0x98, 0x00, 0x51, 0xe4, 0x53, 0xa8,
	0x44, 0x0f, 0xe9, 0x8d, 0x03, 0x82, 0x42, 0x05, 0xbd, 0x00, 0xb2, 0xc5, 0x07, 0x24, 0xf1, 0x84,
	0x58, 0xb8, 0xde, 0xb0, 0xbb, 0x96, 0xc8, 0xe7, 0xc0, 0x89, 0xef, 0xe8, 0xd7, 0xf0, 0x01, 0x7c,
	0x00, 0xda, 0xd9, 0x35, 0x75, 0x20, 0x3d, 0xe4, 0x36, 0xf3, 0xe6, 0xbd, 0x37, 0xb3, 0x9e, 0x31,
	0x74, 0xb2, 0x22, 0xa5, 0x6f, 0x67, 0x2b, 0x29, 0xb4, 0xc0, 0x06, 0x27, 0xd1, 0x0b, 0x38, 0xb9,
	0x32, 0x41, 0x4c, 0x2b, 0xa1, 0x32, 0x2d, 0xe4, 0x3a, 0xa6, 0xaf, 0x25, 0x29, 0x8d, 0x01, 0xf8,
	0xa5, 0xcc, 0x43, 0x6f, 0xe4, 0x8d, 0xdb, 0xb1, 0x09, 0x11, 0x61, 0x7f, 0x39, 0x55, 0xcb, 0x70,
	0x8f, 0x21, 0x8e, 0xa3, 0x73, 0x78, 0xf0, 0x9f, 0x5e, 0xad, 0x44, 0xa1, 0x08, 0x43, 0x68, 0x71,
	0x0f, 0x4a, 0xd9, 0xe4, 0x20, 0xae, 0xd2, 0xe8, 0x39, 0x20, 0x8b, 0x12, 0x3d, 0xd5, 0xa5, 0xda,
	0xad, 0xe1, 0x4b, 0xe8, 0x6f, 0x68, 0x5d, 0xb3, 0xa7, 0xd0, 0x54, 0x8c, 0x84, 0xfe, 0xc8, 0x1b,
	0x77, 0x27, 0xbd, 0x33, 0xfb, 0x58, 0x4b, 0x7b, 0x2d, 0x52, 0x8a, 0x1d, 0x21, 0x4a, 0xa0, 0x9f,
	0xd0, 0x54, 0xce, 0x97, 0xc9, 0xfa, 0x7a, 0x26, 0xf2, 0x9d, 0xda, 0xe3, 0x09, 0x34, 0x15, 0xcb,
	0xb8, 0x4f, 0x3b, 0x76, 0x59, 0x74, 0x09, 0xf7, 0x37, 0x4d, 0xdd, 0x5c, 0xcf, 0xa0, 0x65, 0x19,
	0x2a, 0xf4, 0x46, 0xfe, 0xb8, 0x33, 0xe9, 0x57, 0x83, 0x55, 0xbc, 0x32, 0xd7, 0x71, 0xc5, 0x89,
	0x7e, 0x7a, 0x70, 0x58, 0xaf, 0x98, 0x19, 0x16, 0x59, 0x4e, 0x6e, 0x2c, 0x8e, 0x71, 0x08, 0x90,
	0x67, 0x05, 0xbd, 0x2f, 0xaf, 0x67, 0x24, 0x79, 0xba, 0x46, 0x5c, 0x43, 0x8c, 0xc6, 0x64, 0x6e,
	0x42, 0x8e, 0x2b, 0xcd, 0x05, 0x2d, 0x84, 0xa4, 0x70, 0x9f, 0x2b, 0x35, 0x04, 0x1f, 0x43, 0xdb,
	0x64, 0xaf, 0x16, 0x9a, 0x64, 0xd8, 0xe0, 0xf2, 0x2d, 0x60, 0x1c, 0xbf, 0x64, 0x45, 0x1a, 0x36,
	0xad, 0xa3, 0x89, 0x4f, 0x3f, 0x40, 0xfb, 0x52, 0x4a, 0x21, 0xcd, 0xb7, 0xc5, 0x0e, 0xb4, 0x92,
	0x72, 0x3e, 0x27, 0xa5, 0x82, 0x7b, 0x88, 0x70, 0x74, 0x55, 0x68, 0x92, 0xc5, 0x34, 0x67, 0x46,
	0xf0, 0xdb, 0xc7, 0x1e, 0x74, 0x78, 0x6d, 0x24, 0x2f, 0x4a, 0xb5, 0x0e, 0xbe, 0xdf, 0x0c, 0xb1,
	0x0b, 0x07, 0x0c, 0x65, 0xc5, 0xe7, 0xe0, 0xc7, 0xcd, 0xf0, 0xf4, 0x1d, 0xc0, 0xed, 0xb6, 0xb0,
	0x0f, 0xc7, 0x36, 0xfb, 0x54, 0x58, 0x61, 0xca, 0xce, 0x5d, 0x0b, 0xfe, 0x15, 0xee, 0x61, 0x0f,
	0x8e, 0x6a, 0x18, 0xa5, 0x81, 0x3f, 0xf9, 0xe5, 0x41, 0x83, 0x33, 0xfc, 0x08, 0xc7, 0xff, 0x9c,
	0x27, 0x3e, 0x71, 0x0b, 0xd8, 0x7e, 0xf6, 0x83, 0xe1, 0x5d, 0x65, 0xb7, 0xd0, 0x37, 0xee, 0x21,
	0xb6, 0x27, 0x3e, 0xac, 0xd3, 0x37, 0xee, 0x79, 0x30, 0xd8, 0x56, 0x72, 0x2e, 0x6f, 0xe1, 0xb0,
	0x7e, 0x2e, 0x58, 0x71, 0xb7, 0x1c, 0xe6, 0xe0, 0xd1, 0xd6, 0x9a, 0x35, 0x9a, 0x35, 0xf9, 0x6f,
	0x3e, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x46, 0xdf, 0xbe, 0x83, 0xdc, 0x03, 0x00, 0x00,
}
