// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gits.proto

package gits

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_Success        ErrorCode = 0
	ErrorCode_RepoUrlInvalid ErrorCode = 100001
	ErrorCode_RepoNotExist   ErrorCode = 100002
	ErrorCode_GitsBusy       ErrorCode = 100003
	ErrorCode_RepoCloning    ErrorCode = 100004
)

var ErrorCode_name = map[int32]string{
	0:      "Success",
	100001: "RepoUrlInvalid",
	100002: "RepoNotExist",
	100003: "GitsBusy",
	100004: "RepoCloning",
}
var ErrorCode_value = map[string]int32{
	"Success":        0,
	"RepoUrlInvalid": 100001,
	"RepoNotExist":   100002,
	"GitsBusy":       100003,
	"RepoCloning":    100004,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{0}
}

type CloneStatus int32

const (
	CloneStatus_Unknown CloneStatus = 0
	CloneStatus_Cloning CloneStatus = 1
	CloneStatus_Cloned  CloneStatus = 2
)

var CloneStatus_name = map[int32]string{
	0: "Unknown",
	1: "Cloning",
	2: "Cloned",
}
var CloneStatus_value = map[string]int32{
	"Unknown": 0,
	"Cloning": 1,
	"Cloned":  2,
}

func (x CloneStatus) String() string {
	return proto.EnumName(CloneStatus_name, int32(x))
}
func (CloneStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{1}
}

type CloneRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloneRequest) Reset()         { *m = CloneRequest{} }
func (m *CloneRequest) String() string { return proto.CompactTextString(m) }
func (*CloneRequest) ProtoMessage()    {}
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{0}
}
func (m *CloneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneRequest.Unmarshal(m, b)
}
func (m *CloneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneRequest.Marshal(b, m, deterministic)
}
func (dst *CloneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneRequest.Merge(dst, src)
}
func (m *CloneRequest) XXX_Size() int {
	return xxx_messageInfo_CloneRequest.Size(m)
}
func (m *CloneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloneRequest proto.InternalMessageInfo

func (m *CloneRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CloneResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloneResponse) Reset()         { *m = CloneResponse{} }
func (m *CloneResponse) String() string { return proto.CompactTextString(m) }
func (*CloneResponse) ProtoMessage()    {}
func (*CloneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{1}
}
func (m *CloneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneResponse.Unmarshal(m, b)
}
func (m *CloneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneResponse.Marshal(b, m, deterministic)
}
func (dst *CloneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneResponse.Merge(dst, src)
}
func (m *CloneResponse) XXX_Size() int {
	return xxx_messageInfo_CloneResponse.Size(m)
}
func (m *CloneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloneResponse proto.InternalMessageInfo

type GetCloneStatusRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCloneStatusRequest) Reset()         { *m = GetCloneStatusRequest{} }
func (m *GetCloneStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetCloneStatusRequest) ProtoMessage()    {}
func (*GetCloneStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{2}
}
func (m *GetCloneStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCloneStatusRequest.Unmarshal(m, b)
}
func (m *GetCloneStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCloneStatusRequest.Marshal(b, m, deterministic)
}
func (dst *GetCloneStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCloneStatusRequest.Merge(dst, src)
}
func (m *GetCloneStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetCloneStatusRequest.Size(m)
}
func (m *GetCloneStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCloneStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCloneStatusRequest proto.InternalMessageInfo

func (m *GetCloneStatusRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GetCloneStatusResponse struct {
	Status               CloneStatus `protobuf:"varint,1,opt,name=status,enum=gits.CloneStatus" json:"status,omitempty"`
	Progress             string      `protobuf:"bytes,2,opt,name=progress" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetCloneStatusResponse) Reset()         { *m = GetCloneStatusResponse{} }
func (m *GetCloneStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetCloneStatusResponse) ProtoMessage()    {}
func (*GetCloneStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{3}
}
func (m *GetCloneStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCloneStatusResponse.Unmarshal(m, b)
}
func (m *GetCloneStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCloneStatusResponse.Marshal(b, m, deterministic)
}
func (dst *GetCloneStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCloneStatusResponse.Merge(dst, src)
}
func (m *GetCloneStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetCloneStatusResponse.Size(m)
}
func (m *GetCloneStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCloneStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCloneStatusResponse proto.InternalMessageInfo

func (m *GetCloneStatusResponse) GetStatus() CloneStatus {
	if m != nil {
		return m.Status
	}
	return CloneStatus_Unknown
}

func (m *GetCloneStatusResponse) GetProgress() string {
	if m != nil {
		return m.Progress
	}
	return ""
}

type ArchiveRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Commit               string   `protobuf:"bytes,2,opt,name=commit" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArchiveRequest) Reset()         { *m = ArchiveRequest{} }
func (m *ArchiveRequest) String() string { return proto.CompactTextString(m) }
func (*ArchiveRequest) ProtoMessage()    {}
func (*ArchiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{4}
}
func (m *ArchiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArchiveRequest.Unmarshal(m, b)
}
func (m *ArchiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArchiveRequest.Marshal(b, m, deterministic)
}
func (dst *ArchiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArchiveRequest.Merge(dst, src)
}
func (m *ArchiveRequest) XXX_Size() int {
	return xxx_messageInfo_ArchiveRequest.Size(m)
}
func (m *ArchiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArchiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArchiveRequest proto.InternalMessageInfo

func (m *ArchiveRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ArchiveRequest) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

type ArchiveResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArchiveResponse) Reset()         { *m = ArchiveResponse{} }
func (m *ArchiveResponse) String() string { return proto.CompactTextString(m) }
func (*ArchiveResponse) ProtoMessage()    {}
func (*ArchiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{5}
}
func (m *ArchiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArchiveResponse.Unmarshal(m, b)
}
func (m *ArchiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArchiveResponse.Marshal(b, m, deterministic)
}
func (dst *ArchiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArchiveResponse.Merge(dst, src)
}
func (m *ArchiveResponse) XXX_Size() int {
	return xxx_messageInfo_ArchiveResponse.Size(m)
}
func (m *ArchiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArchiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArchiveResponse proto.InternalMessageInfo

func (m *ArchiveResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetNamedCommitsRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNamedCommitsRequest) Reset()         { *m = GetNamedCommitsRequest{} }
func (m *GetNamedCommitsRequest) String() string { return proto.CompactTextString(m) }
func (*GetNamedCommitsRequest) ProtoMessage()    {}
func (*GetNamedCommitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{6}
}
func (m *GetNamedCommitsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNamedCommitsRequest.Unmarshal(m, b)
}
func (m *GetNamedCommitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNamedCommitsRequest.Marshal(b, m, deterministic)
}
func (dst *GetNamedCommitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNamedCommitsRequest.Merge(dst, src)
}
func (m *GetNamedCommitsRequest) XXX_Size() int {
	return xxx_messageInfo_GetNamedCommitsRequest.Size(m)
}
func (m *GetNamedCommitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNamedCommitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNamedCommitsRequest proto.InternalMessageInfo

func (m *GetNamedCommitsRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GetNamedCommitsResponse struct {
	Commits              []*NamedCommit `protobuf:"bytes,1,rep,name=commits" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetNamedCommitsResponse) Reset()         { *m = GetNamedCommitsResponse{} }
func (m *GetNamedCommitsResponse) String() string { return proto.CompactTextString(m) }
func (*GetNamedCommitsResponse) ProtoMessage()    {}
func (*GetNamedCommitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{7}
}
func (m *GetNamedCommitsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNamedCommitsResponse.Unmarshal(m, b)
}
func (m *GetNamedCommitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNamedCommitsResponse.Marshal(b, m, deterministic)
}
func (dst *GetNamedCommitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNamedCommitsResponse.Merge(dst, src)
}
func (m *GetNamedCommitsResponse) XXX_Size() int {
	return xxx_messageInfo_GetNamedCommitsResponse.Size(m)
}
func (m *GetNamedCommitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNamedCommitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNamedCommitsResponse proto.InternalMessageInfo

func (m *GetNamedCommitsResponse) GetCommits() []*NamedCommit {
	if m != nil {
		return m.Commits
	}
	return nil
}

type GetRepositoryFilesRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Commit               string   `protobuf:"bytes,2,opt,name=commit" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRepositoryFilesRequest) Reset()         { *m = GetRepositoryFilesRequest{} }
func (m *GetRepositoryFilesRequest) String() string { return proto.CompactTextString(m) }
func (*GetRepositoryFilesRequest) ProtoMessage()    {}
func (*GetRepositoryFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{8}
}
func (m *GetRepositoryFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRepositoryFilesRequest.Unmarshal(m, b)
}
func (m *GetRepositoryFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRepositoryFilesRequest.Marshal(b, m, deterministic)
}
func (dst *GetRepositoryFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRepositoryFilesRequest.Merge(dst, src)
}
func (m *GetRepositoryFilesRequest) XXX_Size() int {
	return xxx_messageInfo_GetRepositoryFilesRequest.Size(m)
}
func (m *GetRepositoryFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRepositoryFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRepositoryFilesRequest proto.InternalMessageInfo

func (m *GetRepositoryFilesRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetRepositoryFilesRequest) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

type GetRepositoryFilesResponse struct {
	Entries              []*FileEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetRepositoryFilesResponse) Reset()         { *m = GetRepositoryFilesResponse{} }
func (m *GetRepositoryFilesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRepositoryFilesResponse) ProtoMessage()    {}
func (*GetRepositoryFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{9}
}
func (m *GetRepositoryFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRepositoryFilesResponse.Unmarshal(m, b)
}
func (m *GetRepositoryFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRepositoryFilesResponse.Marshal(b, m, deterministic)
}
func (dst *GetRepositoryFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRepositoryFilesResponse.Merge(dst, src)
}
func (m *GetRepositoryFilesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRepositoryFilesResponse.Size(m)
}
func (m *GetRepositoryFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRepositoryFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRepositoryFilesResponse proto.InternalMessageInfo

func (m *GetRepositoryFilesResponse) GetEntries() []*FileEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type GetRepositoryBlobRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Commit               string   `protobuf:"bytes,2,opt,name=commit" json:"commit,omitempty"`
	File                 string   `protobuf:"bytes,3,opt,name=file" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRepositoryBlobRequest) Reset()         { *m = GetRepositoryBlobRequest{} }
func (m *GetRepositoryBlobRequest) String() string { return proto.CompactTextString(m) }
func (*GetRepositoryBlobRequest) ProtoMessage()    {}
func (*GetRepositoryBlobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{10}
}
func (m *GetRepositoryBlobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRepositoryBlobRequest.Unmarshal(m, b)
}
func (m *GetRepositoryBlobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRepositoryBlobRequest.Marshal(b, m, deterministic)
}
func (dst *GetRepositoryBlobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRepositoryBlobRequest.Merge(dst, src)
}
func (m *GetRepositoryBlobRequest) XXX_Size() int {
	return xxx_messageInfo_GetRepositoryBlobRequest.Size(m)
}
func (m *GetRepositoryBlobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRepositoryBlobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRepositoryBlobRequest proto.InternalMessageInfo

func (m *GetRepositoryBlobRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetRepositoryBlobRequest) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *GetRepositoryBlobRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

type GetRepositoryBlobResponse struct {
	Content              string   `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	Plain                bool     `protobuf:"varint,2,opt,name=plain" json:"plain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRepositoryBlobResponse) Reset()         { *m = GetRepositoryBlobResponse{} }
func (m *GetRepositoryBlobResponse) String() string { return proto.CompactTextString(m) }
func (*GetRepositoryBlobResponse) ProtoMessage()    {}
func (*GetRepositoryBlobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{11}
}
func (m *GetRepositoryBlobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRepositoryBlobResponse.Unmarshal(m, b)
}
func (m *GetRepositoryBlobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRepositoryBlobResponse.Marshal(b, m, deterministic)
}
func (dst *GetRepositoryBlobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRepositoryBlobResponse.Merge(dst, src)
}
func (m *GetRepositoryBlobResponse) XXX_Size() int {
	return xxx_messageInfo_GetRepositoryBlobResponse.Size(m)
}
func (m *GetRepositoryBlobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRepositoryBlobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRepositoryBlobResponse proto.InternalMessageInfo

func (m *GetRepositoryBlobResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *GetRepositoryBlobResponse) GetPlain() bool {
	if m != nil {
		return m.Plain
	}
	return false
}

type NamedCommit struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Branch               bool     `protobuf:"varint,3,opt,name=branch" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedCommit) Reset()         { *m = NamedCommit{} }
func (m *NamedCommit) String() string { return proto.CompactTextString(m) }
func (*NamedCommit) ProtoMessage()    {}
func (*NamedCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{12}
}
func (m *NamedCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedCommit.Unmarshal(m, b)
}
func (m *NamedCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedCommit.Marshal(b, m, deterministic)
}
func (dst *NamedCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedCommit.Merge(dst, src)
}
func (m *NamedCommit) XXX_Size() int {
	return xxx_messageInfo_NamedCommit.Size(m)
}
func (m *NamedCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedCommit.DiscardUnknown(m)
}

var xxx_messageInfo_NamedCommit proto.InternalMessageInfo

func (m *NamedCommit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedCommit) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *NamedCommit) GetBranch() bool {
	if m != nil {
		return m.Branch
	}
	return false
}

type FileEntry struct {
	File                 string   `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Dir                  bool     `protobuf:"varint,2,opt,name=dir" json:"dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileEntry) Reset()         { *m = FileEntry{} }
func (m *FileEntry) String() string { return proto.CompactTextString(m) }
func (*FileEntry) ProtoMessage()    {}
func (*FileEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_gits_4bc68d6fa6ca183e, []int{13}
}
func (m *FileEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileEntry.Unmarshal(m, b)
}
func (m *FileEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileEntry.Marshal(b, m, deterministic)
}
func (dst *FileEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileEntry.Merge(dst, src)
}
func (m *FileEntry) XXX_Size() int {
	return xxx_messageInfo_FileEntry.Size(m)
}
func (m *FileEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FileEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FileEntry proto.InternalMessageInfo

func (m *FileEntry) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *FileEntry) GetDir() bool {
	if m != nil {
		return m.Dir
	}
	return false
}

func init() {
	proto.RegisterType((*CloneRequest)(nil), "gits.CloneRequest")
	proto.RegisterType((*CloneResponse)(nil), "gits.CloneResponse")
	proto.RegisterType((*GetCloneStatusRequest)(nil), "gits.GetCloneStatusRequest")
	proto.RegisterType((*GetCloneStatusResponse)(nil), "gits.GetCloneStatusResponse")
	proto.RegisterType((*ArchiveRequest)(nil), "gits.ArchiveRequest")
	proto.RegisterType((*ArchiveResponse)(nil), "gits.ArchiveResponse")
	proto.RegisterType((*GetNamedCommitsRequest)(nil), "gits.GetNamedCommitsRequest")
	proto.RegisterType((*GetNamedCommitsResponse)(nil), "gits.GetNamedCommitsResponse")
	proto.RegisterType((*GetRepositoryFilesRequest)(nil), "gits.GetRepositoryFilesRequest")
	proto.RegisterType((*GetRepositoryFilesResponse)(nil), "gits.GetRepositoryFilesResponse")
	proto.RegisterType((*GetRepositoryBlobRequest)(nil), "gits.GetRepositoryBlobRequest")
	proto.RegisterType((*GetRepositoryBlobResponse)(nil), "gits.GetRepositoryBlobResponse")
	proto.RegisterType((*NamedCommit)(nil), "gits.NamedCommit")
	proto.RegisterType((*FileEntry)(nil), "gits.FileEntry")
	proto.RegisterEnum("gits.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("gits.CloneStatus", CloneStatus_name, CloneStatus_value)
}

func init() { proto.RegisterFile("gits.proto", fileDescriptor_gits_4bc68d6fa6ca183e) }

var fileDescriptor_gits_4bc68d6fa6ca183e = []byte{
	// 608 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdb, 0x4e, 0xdb, 0x40,
	0x10, 0x25, 0x04, 0x9c, 0x30, 0xa1, 0x89, 0x99, 0x02, 0x4d, 0xdd, 0x0b, 0xc8, 0x52, 0x25, 0xa0,
	0x12, 0xa2, 0xf0, 0x52, 0xf5, 0xad, 0xa0, 0x10, 0x55, 0xa8, 0x79, 0x30, 0x45, 0xed, 0x5b, 0xe5,
	0xc4, 0xdb, 0x64, 0x55, 0x67, 0x37, 0xdd, 0xdd, 0xd0, 0xe6, 0x23, 0xf2, 0x11, 0xbd, 0x7c, 0x47,
	0xbf, 0xad, 0xda, 0xf5, 0xda, 0x38, 0x89, 0x53, 0x89, 0xb7, 0x99, 0xd9, 0x33, 0x67, 0xce, 0xec,
	0xfa, 0x18, 0xa0, 0x4f, 0x95, 0x3c, 0x1e, 0x09, 0xae, 0x38, 0xae, 0xe9, 0xd8, 0xdf, 0x87, 0xcd,
	0x8b, 0x98, 0x33, 0x12, 0x90, 0x6f, 0x63, 0x22, 0x15, 0xba, 0x50, 0x1e, 0x8b, 0xb8, 0x59, 0xda,
	0x2f, 0x1d, 0x6c, 0x04, 0x3a, 0xf4, 0x1b, 0xf0, 0xc0, 0x22, 0xe4, 0x88, 0x33, 0x49, 0xfc, 0x43,
	0xd8, 0x69, 0x13, 0x65, 0x6a, 0xd7, 0x2a, 0x54, 0x63, 0xb9, 0xbc, 0xf7, 0x33, 0xec, 0xce, 0x43,
	0x13, 0x12, 0x3c, 0x04, 0x47, 0x9a, 0x8a, 0x81, 0xd7, 0x4f, 0xb7, 0x8e, 0x8d, 0xb4, 0x3c, 0xd4,
	0x02, 0xd0, 0x83, 0xea, 0x48, 0xf0, 0xbe, 0x20, 0x52, 0x36, 0x57, 0x0d, 0x77, 0x96, 0xfb, 0x6f,
	0xa0, 0xfe, 0x56, 0xf4, 0x06, 0xf4, 0x76, 0xf9, 0x02, 0xb8, 0x0b, 0x4e, 0x8f, 0x0f, 0x87, 0x54,
	0xd9, 0x6e, 0x9b, 0xf9, 0x2f, 0xa0, 0x91, 0xf5, 0x5a, 0x55, 0x08, 0x6b, 0x51, 0xa8, 0x42, 0xd3,
	0xbd, 0x19, 0x98, 0xd8, 0x3f, 0x32, 0x3b, 0x74, 0xc2, 0x21, 0x89, 0x2e, 0x4c, 0xe3, 0x7f, 0xf6,
	0xbd, 0x84, 0x47, 0x0b, 0x58, 0x4b, 0xfd, 0x12, 0x2a, 0xc9, 0x5c, 0xbd, 0x71, 0xf9, 0xa0, 0x96,
	0x6e, 0x9c, 0x03, 0x07, 0x29, 0xc2, 0x6f, 0xc1, 0xe3, 0x36, 0x51, 0x01, 0x19, 0x71, 0x49, 0x15,
	0x17, 0x93, 0x4b, 0x1a, 0x13, 0x79, 0xff, 0x0d, 0xdb, 0xe0, 0x15, 0xd1, 0x64, 0x4f, 0x50, 0x21,
	0x4c, 0x09, 0x4a, 0x52, 0x45, 0x8d, 0x44, 0x91, 0x46, 0xb5, 0x98, 0x12, 0x93, 0x20, 0x3d, 0xf7,
	0x3f, 0x41, 0x73, 0x86, 0xe8, 0x3c, 0xe6, 0xdd, 0x7b, 0xcb, 0xd1, 0xb7, 0xfb, 0x85, 0xc6, 0xa4,
	0x59, 0x36, 0x55, 0x13, 0xfb, 0x57, 0x73, 0x9b, 0x26, 0xcc, 0x56, 0x61, 0x53, 0xdf, 0x19, 0x53,
	0x84, 0x29, 0x4b, 0x9f, 0xa6, 0xb8, 0x0d, 0xeb, 0xa3, 0x38, 0xa4, 0xcc, 0x4c, 0xa8, 0x06, 0x49,
	0xe2, 0xbf, 0x87, 0x5a, 0xee, 0x3a, 0xf5, 0x3c, 0x16, 0x0e, 0x89, 0xed, 0x35, 0xb1, 0xae, 0x0d,
	0x42, 0x39, 0xb0, 0xca, 0x4c, 0xac, 0xf5, 0x76, 0x45, 0xc8, 0x7a, 0x03, 0xa3, 0xac, 0x1a, 0xd8,
	0xcc, 0x7f, 0x05, 0x1b, 0xd9, 0x5d, 0x64, 0xe2, 0x4b, 0x77, 0xe2, 0xf5, 0xea, 0x11, 0x15, 0x56,
	0x83, 0x0e, 0x8f, 0x08, 0x6c, 0xb4, 0x84, 0xe0, 0xe2, 0x82, 0x47, 0x04, 0x6b, 0x50, 0xb9, 0x1e,
	0xf7, 0x7a, 0x44, 0x4a, 0x77, 0x05, 0xb7, 0xa1, 0xae, 0xb7, 0xbc, 0x11, 0xf1, 0x3b, 0x76, 0x1b,
	0xc6, 0x34, 0x72, 0x7f, 0x4e, 0x1d, 0x44, 0xd8, 0xd4, 0xd5, 0x0e, 0x57, 0xad, 0x1f, 0x54, 0x2a,
	0xf7, 0xd7, 0xd4, 0xc1, 0x3a, 0x54, 0xdb, 0x54, 0xc9, 0xf3, 0xb1, 0x9c, 0xb8, 0xbf, 0xa7, 0x0e,
	0x6e, 0x41, 0x4d, 0x63, 0xb4, 0x35, 0x28, 0xeb, 0xbb, 0x7f, 0xa6, 0xce, 0xd1, 0x19, 0xd4, 0x72,
	0x4e, 0xd1, 0x83, 0x6e, 0xd8, 0x57, 0xc6, 0xbf, 0x33, 0x77, 0x45, 0x27, 0x29, 0xb4, 0x84, 0x00,
	0x8e, 0x01, 0x46, 0xee, 0xea, 0xe9, 0xdf, 0x32, 0xac, 0x69, 0x62, 0x3c, 0x81, 0x75, 0x53, 0x44,
	0xcc, 0x99, 0xce, 0x3e, 0xa7, 0xf7, 0x70, 0xa6, 0x66, 0x1f, 0xe2, 0x0a, 0xea, 0xb3, 0x3e, 0xc6,
	0x27, 0x09, 0xac, 0xf0, 0x47, 0xe0, 0x3d, 0x2d, 0x3e, 0xb4, 0x64, 0xaf, 0xa1, 0x62, 0x7d, 0x87,
	0xdb, 0x09, 0x70, 0xd6, 0xc2, 0xde, 0xce, 0x5c, 0x35, 0xe9, 0x3b, 0x29, 0x61, 0x07, 0x1a, 0x73,
	0xf6, 0xc2, 0xbb, 0x51, 0x05, 0x0e, 0xf5, 0x9e, 0x2d, 0x39, 0xb5, 0x4a, 0x3e, 0x02, 0x2e, 0xfa,
	0x03, 0xf7, 0xb2, 0xa6, 0x62, 0x03, 0x7a, 0xfb, 0xcb, 0x01, 0x96, 0xf8, 0x03, 0x6c, 0x2d, 0x7c,
	0xd5, 0xf8, 0xbc, 0xa0, 0x2d, 0x67, 0x24, 0x6f, 0x6f, 0xe9, 0x79, 0xc2, 0xda, 0x75, 0xcc, 0x8f,
	0xfb, 0xec, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x28, 0xa3, 0x4c, 0x41, 0xc6, 0x05, 0x00, 0x00,
}
